1. create audit, which will be under security\audits folder in SSMS

USE [master]
GO

/****** Object:  Audit [Audit-20160908-102315]    Script Date: 9/9/2016 3:46:47 PM ******/
CREATE SERVER AUDIT [Audit-20160908-102315]
TO FILE 
(	FILEPATH = N'K:\Audit\'
	,MAXSIZE = 0 MB
	,MAX_ROLLOVER_FILES = 2147483647
	,RESERVE_DISK_SPACE = OFF
)
WITH
(	QUEUE_DELAY = 0
	,ON_FAILURE = CONTINUE
	,AUDIT_GUID = 'b2f2c6ef-975f-48ae-8c75-1aea9e675403'
)
ALTER SERVER AUDIT [Audit-20160908-102315] WITH (STATE = ON)
GO


2. create server audit specification which will be under security\Server Audit Specifications folder in SSMS

USE [master]
GO

CREATE SERVER AUDIT SPECIFICATION [ServerAuditSpecification-20160908-105921]
FOR SERVER AUDIT [Audit-20160908-102315]
ADD (SERVER_PERMISSION_CHANGE_GROUP),
ADD (FAILED_LOGIN_GROUP)
WITH (STATE = ON)
GO

TO be monitored Server-Level Audit Action Groups

DATABASE_CHANGE_GROUP
DATABASE_OBJECT_PERMISSION_CHANGE_GROUP
DATABASE_OWNERSHIP_CHANGE_GROUP
DATABASE_PERMISSION_CHANGE_GROUP
DATABASE_PRINCIPAL_CHANGE_GROUP
DATABASE_ROLE_MEMBER_CHANGE_GROUP

FAILED_LOGIN_GROUP

SERVER_OBJECT_PERMISSION_CHANGE_GROUP
SERVER_OBJECT_OWNERSHIP_CHANGE_GROUP
SERVER_PERMISSION_CHANGE_GROUP
SERVER_PRINCIPAL_CHANGE_GROUP
SERVER_ROLE_MEMBER_CHANGE_GROUP
SERVER_STATE_CHANGE_GROUP


3. create database audit specifications which will be under <database>\Security\Database audit Specifications folder in SSMS

USE [CMDB_V2]
GO

CREATE DATABASE AUDIT SPECIFICATION [DatabaseAuditSpecification-20160909-145447]
FOR SERVER AUDIT [Audit-20160908-102315]
ADD (SELECT ON OBJECT::[dbo].[tbl_database] BY [dbo])
WITH (STATE = ON)
GO



