if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[qryJrnlDetails]') and OBJECTPROPERTY(id, N'IsView') = 1)
drop view [dbo].[qryJrnlDetails]
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[PS_VCHR_ACCT_DRILL]') and OBJECTPROPERTY(id, N'IsView') = 1)
drop view [dbo].[PS_VCHR_ACCT_DRILL]
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[PS_VCHR_JRNL_VW]') and OBJECTPROPERTY(id, N'IsView') = 1)
drop view [dbo].[PS_VCHR_JRNL_VW]
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[qryApplicationSettings_BlankRecordKeys]') and OBJECTPROPERTY(id, N'IsView') = 1)
drop view [dbo].[qryApplicationSettings_BlankRecordKeys]
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[qryApplicationSettings_CurrentProfileSpecificSettings]') and OBJECTPROPERTY(id, N'IsView') = 1)
drop view [dbo].[qryApplicationSettings_CurrentProfileSpecificSettings]
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[qryApplicationSettings_DtsLoadSimpleTables]') and OBJECTPROPERTY(id, N'IsView') = 1)
drop view [dbo].[qryApplicationSettings_DtsLoadSimpleTables]
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[qryApplicationSettings_Errors]') and OBJECTPROPERTY(id, N'IsView') = 1)
drop view [dbo].[qryApplicationSettings_Errors]
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[qryApplicationSettings_Filters]') and OBJECTPROPERTY(id, N'IsView') = 1)
drop view [dbo].[qryApplicationSettings_Filters]
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[qryApplicationSettings_Scripts]') and OBJECTPROPERTY(id, N'IsView') = 1)
drop view [dbo].[qryApplicationSettings_Scripts]
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[qryApplicationSettings_ServersAndDatabases]') and OBJECTPROPERTY(id, N'IsView') = 1)
drop view [dbo].[qryApplicationSettings_ServersAndDatabases]
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[qryApplicationSettings_Statistics]') and OBJECTPROPERTY(id, N'IsView') = 1)
drop view [dbo].[qryApplicationSettings_Statistics]
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[qryApplicationSettings_TruncateSettings]') and OBJECTPROPERTY(id, N'IsView') = 1)
drop view [dbo].[qryApplicationSettings_TruncateSettings]
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[qryDetailSourceLookups_MissingDetailSourceNames]') and OBJECTPROPERTY(id, N'IsView') = 1)
drop view [dbo].[qryDetailSourceLookups_MissingDetailSourceNames]
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[qryDetails]') and OBJECTPROPERTY(id, N'IsView') = 1)
drop view [dbo].[qryDetails]
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[qryJrnlDetails_AMG]') and OBJECTPROPERTY(id, N'IsView') = 1)
drop view [dbo].[qryJrnlDetails_AMG]
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[qryJrnlDetails_IFX]') and OBJECTPROPERTY(id, N'IsView') = 1)
drop view [dbo].[qryJrnlDetails_IFX]
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[PS_INQ_JRNL_TRN_VW]') and OBJECTPROPERTY(id, N'IsView') = 1)
drop view [dbo].[PS_INQ_JRNL_TRN_VW]
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[PS_JRNL_HEADER_linked]') and OBJECTPROPERTY(id, N'IsView') = 1)
drop view [dbo].[PS_JRNL_HEADER_linked]
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[PS_JRNL_LN_linked]') and OBJECTPROPERTY(id, N'IsView') = 1)
drop view [dbo].[PS_JRNL_LN_linked]
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[qryAMDetails]') and OBJECTPROPERTY(id, N'IsView') = 1)
drop view [dbo].[qryAMDetails]
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[qryAPDetails]') and OBJECTPROPERTY(id, N'IsView') = 1)
drop view [dbo].[qryAPDetails]
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[qryDetailSourceCombinations]') and OBJECTPROPERTY(id, N'IsView') = 1)
drop view [dbo].[qryDetailSourceCombinations]
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[qryDistinctDetailSources]') and OBJECTPROPERTY(id, N'IsView') = 1)
drop view [dbo].[qryDistinctDetailSources]
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[qryIFXDetails]') and OBJECTPROPERTY(id, N'IsView') = 1)
drop view [dbo].[qryIFXDetails]
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[qryINDetails]') and OBJECTPROPERTY(id, N'IsView') = 1)
drop view [dbo].[qryINDetails]
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[qryJrnlDetails_APG]') and OBJECTPROPERTY(id, N'IsView') = 1)
drop view [dbo].[qryJrnlDetails_APG]
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[qryJrnlDetails_ING]') and OBJECTPROPERTY(id, N'IsView') = 1)
drop view [dbo].[qryJrnlDetails_ING]
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[qryJrnlDetails_ONL]') and OBJECTPROPERTY(id, N'IsView') = 1)
drop view [dbo].[qryJrnlDetails_ONL]
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[qryJrnlDetails_PO]') and OBJECTPROPERTY(id, N'IsView') = 1)
drop view [dbo].[qryJrnlDetails_PO]
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[qryJrnlDetails_PYG]') and OBJECTPROPERTY(id, N'IsView') = 1)
drop view [dbo].[qryJrnlDetails_PYG]
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[qryPODetails]') and OBJECTPROPERTY(id, N'IsView') = 1)
drop view [dbo].[qryPODetails]
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[qryPYDetails]') and OBJECTPROPERTY(id, N'IsView') = 1)
drop view [dbo].[qryPYDetails]
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[z_qryINVTest]') and OBJECTPROPERTY(id, N'IsView') = 1)
drop view [dbo].[z_qryINVTest]
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO




CREATE VIEW PS_INQ_JRNL_TRN_VW
	(JOURNAL_ID, JOURNAL_DATE, FISCAL_YEAR, 
	ACCOUNTING_PERIOD, BUSINESS_UNIT, LEDGER, 
	UNPOST_SEQ, JOURNAL_LINE, ACCOUNT, 
	ALTACCT, DEPTID, OPERATING_UNIT, 
	PRODUCT, FUND_CODE, CLASS_FLD, 
	PROGRAM_CODE, BUDGET_REF, AFFILIATE, 
	AFFILIATE_INTRA1, AFFILIATE_INTRA2, CHARTFIELD1, 
	CHARTFIELD2, CHARTFIELD3, PROJECT_ID, 
	BUSINESS_UNIT_PC, ACTIVITY_ID, RESOURCE_TYPE, 
	BUDGET_PERIOD, BOOK_CODE, GL_ADJUST_TYPE, 
	SCENARIO, STATISTICS_CODE, SOURCE, 
	JRNL_HDR_STATUS, ACCTG_DEF_NAME, MONETARY_AMOUNT, 
	CURRENCY_CD, STATISTIC_AMOUNT, FOREIGN_AMOUNT, 
	FOREIGN_CURRENCY, MOVEMENT_FLAG, DISP_CURRENCY) 
AS 
SELECT 
	A.JOURNAL_ID, A.JOURNAL_DATE, B.FISCAL_YEAR, 
	B.ACCOUNTING_PERIOD, B.BUSINESS_UNIT, A.LEDGER, 
	A.UNPOST_SEQ, A.JOURNAL_LINE, A.ACCOUNT, 
	A.ALTACCT, A.DEPTID, A.OPERATING_UNIT, 
	A.PRODUCT, A.FUND_CODE, A.CLASS_FLD, 
	A.PROGRAM_CODE, A.BUDGET_REF, A.AFFILIATE, 
	A.AFFILIATE_INTRA1, A.AFFILIATE_INTRA2, A.CHARTFIELD1, 
	A.CHARTFIELD2, A.CHARTFIELD3, A.PROJECT_ID, 
	A.BUSINESS_UNIT_PC, A.ACTIVITY_ID, A.RESOURCE_TYPE, 
	' ', A.BOOK_CODE, A.GL_ADJUST_TYPE, 
	A.SCENARIO, A.STATISTICS_CODE, B.SOURCE, 
	B.JRNL_HDR_STATUS, B.ACCTG_DEF_NAME, A.MONETARY_AMOUNT, 
	A.CURRENCY_CD, A.STATISTIC_AMOUNT, A.FOREIGN_AMOUNT, 
	A.FOREIGN_CURRENCY, A.MOVEMENT_FLAG, '' 
FROM 
	PS_JRNL_LN A, 
	PS_JRNL_HEADER B 
WHERE 
	A.BUSINESS_UNIT = B.BUSINESS_UNIT 
	AND A.JOURNAL_ID = B.JOURNAL_ID 
	AND A.JOURNAL_DATE = B.JOURNAL_DATE 
	AND A.UNPOST_SEQ = B.UNPOST_SEQ 
	AND B.JRNL_HDR_STATUS IN ('P', 'U')

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO



CREATE  view PS_JRNL_HEADER_linked as
SELECT BUSINESS_UNIT, JOURNAL_ID, JOURNAL_DATE, UNPOST_SEQ, FISCAL_YEAR,
       ACCOUNTING_PERIOD, LEDGER, REVERSAL_CD, SOURCE, JRNL_HDR_STATUS,
       DESCR, SYSTEM_SOURCE, ACCTG_DEF_NAME
FROM   PHSAPSD4.FS84TST.dbo.PS_JRNL_HEADER
/*WHERE FISCAL_YEAR = dbo.fnsAppSetting('FilterForFiscalYearUptoAndIncluding')
       AND ACCOUNTING_PERIOD BETWEEN CONVERT(SMALLINT, dbo.fnsAppSetting('Period')) AND dbo.fnsAppSetting('FilterForPeriodUptoAndIncluding')*/
 






GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO



CREATE view PS_JRNL_LN_linked AS
SELECT L.BUSINESS_UNIT, L.JOURNAL_ID, L.JOURNAL_DATE, L.UNPOST_SEQ, JOURNAL_LINE,
       L.LEDGER, ACCOUNT, DEPTID, OPERATING_UNIT, FUND_CODE, AFFILIATE,
       AFFILIATE_INTRA1, CHARTFIELD1, PROJECT_ID, L.CURRENCY_CD, STATISTICS_CODE,
       MONETARY_AMOUNT, STATISTIC_AMOUNT, JRNL_LN_REF, LINE_DESCR, 
       JRNL_LINE_STATUS, JRNL_LINE_SOURCE
FROM   PHSAPSD4.FS84TST.dbo.PS_JRNL_LN L 
WHERE ((L.CURRENCY_CD = 'CAD') OR (L.CURRENCY_CD = ''))            
       AND ((L.STATISTICS_CODE = 'HRS') OR (L.STATISTICS_CODE = ''))
	








GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

CREATE VIEW qryAMDetails
AS

SELECT 
PS_DIST_LN.AMOUNT AS MONETARY_AMOUNT,
NULL AS STATISTIC_AMOUNT,
PS_DIST_LN.GL_DISTRIB_STATUS AS GL_DISTRIB_STATUS,
PS_DIST_LN.JOURNAL_ID AS JOURNAL_ID,
PS_DIST_LN.JOURNAL_LINE AS JOURNAL_LINE,
NULL AS JRNL_LN_REF,
PS_DIST_LN.BOOK AS PH_REF_CHAR_01,
'AssetID: ' + PS_DIST_LN.ASSET_ID AS PH_REF_CHAR_02,
ACQ.DESCR AS PH_REF_CHAR_03,
RTRIM(PS_DIST_LN.CHARTFIELD2) + '-' + RTRIM(PS_DIST_LN.CHARTFIELD3) AS PH_REF_CHAR_04,
'Cap:'+RTRIM(PS_ASSET.CAP_NUM)+'-'+CONVERT(VARCHAR(5),PS_ASSET.CAP_SEQUENCE) AS PH_REF_CHAR_05, -- Replaced TYPE 2004-10-27
'Last PO:' + RTRIM(ACQ.BUSINESS_UNIT_PO) + '-' + RTRIM(ACQ.PO_ID) + ' Ln:' + CONVERT(VARCHAR(5),ACQ.PO_LINE_NBR) AS PH_REF_CHAR_06
FROM PHSAPSD4.FS84TST.dbo.PS_DIST_LN PS_DIST_LN 
LEFT JOIN PHSAPSD4.FS84TST.dbo.PS_ASSET_ACQ_DET ACQ
ON PS_DIST_LN.BUSINESS_UNIT = ACQ.BUSINESS_UNIT AND PS_DIST_LN.ASSET_ID = ACQ.ASSET_ID
LEFT JOIN PHSAPSD4.FS84TST.dbo.PS_ASSET PS_ASSET
ON PS_DIST_LN.BUSINESS_UNIT = PS_ASSET.BUSINESS_UNIT
AND PS_DIST_LN.ASSET_ID = PS_ASSET.ASSET_ID
WHERE ACQ.SEQUENCE_NBR_6 = (SELECT MAX(ACQ_SN.SEQUENCE_NBR_6) 
                                FROM PHSAPSD4.FS84TST.dbo.PS_ASSET_ACQ_DET ACQ_SN
                                WHERE ACQ.BUSINESS_UNIT = ACQ_SN.BUSINESS_UNIT AND ACQ.ASSET_ID = ACQ_SN.ASSET_ID)


--CHANGED AJ on 2004-10-27
/*SELECT 
PS_DIST_LN.AMOUNT AS MONETARY_AMOUNT,
NULL AS STATISTIC_AMOUNT,
PS_DIST_LN.GL_DISTRIB_STATUS AS GL_DISTRIB_STATUS,
PS_DIST_LN.JOURNAL_ID AS JOURNAL_ID,
PS_DIST_LN.JOURNAL_LINE AS JOURNAL_LINE,
NULL AS JRNL_LN_REF,
PS_DIST_LN.BOOK AS PH_REF_CHAR_01,
'AssetID: ' + PS_DIST_LN.ASSET_ID AS PH_REF_CHAR_02,
ACQ.DESCR AS PH_REF_CHAR_03,
RTRIM(PS_DIST_LN.CHARTFIELD2) + '-' + RTRIM(PS_DIST_LN.CHARTFIELD3) AS PH_REF_CHAR_04,
'Type: ' + PS_DIST_LN.DISTRIBUTION_TYPE + '-' + PS_DIST_LN.TRANS_TYPE + '/' + PS_DIST_LN.CATEGORY AS PH_REF_CHAR_05,
'Last PO:' + RTRIM(ACQ.BUSINESS_UNIT_PO) + '-' + RTRIM(ACQ.PO_ID) + ' Ln:' + CONVERT(VARCHAR(5),ACQ.PO_LINE_NBR) AS PH_REF_CHAR_06
FROM PHSAPSD4.FS84TST.dbo.PS_DIST_LN PS_DIST_LN 
LEFT JOIN PHSAPSD4.FS84TST.dbo.PS_ASSET_ACQ_DET ACQ
ON PS_DIST_LN.BUSINESS_UNIT = ACQ.BUSINESS_UNIT AND PS_DIST_LN.ASSET_ID = ACQ.ASSET_ID
WHERE ACQ.SEQUENCE_NBR_6 = (SELECT MAX(ACQ_SN.SEQUENCE_NBR_6) 
                                FROM PHSAPSD4.FS84TST.dbo.PS_ASSET_ACQ_DET ACQ_SN
                                WHERE ACQ.BUSINESS_UNIT = ACQ_SN.BUSINESS_UNIT AND ACQ.ASSET_ID = ACQ_SN.ASSET_ID)
*/

-- CHANGED AJ on 2004-10-08
/*SELECT 
PS_DIST_LN.AMOUNT AS MONETARY_AMOUNT,
NULL AS STATISTIC_AMOUNT,
PS_DIST_LN.GL_DISTRIB_STATUS AS GL_DISTRIB_STATUS,
PS_DIST_LN.JOURNAL_ID AS JOURNAL_ID,
PS_DIST_LN.JOURNAL_LINE AS JOURNAL_LINE,
NULL AS JRNL_LN_REF,
PS_DIST_LN.BOOK AS PH_REF_CHAR_01,
'AssetID: ' + PS_DIST_LN.ASSET_ID AS PH_REF_CHAR_02,
PS_ASSET.DESCR AS PH_REF_CHAR_03,
RTRIM(PS_DIST_LN.CHARTFIELD2) + '-' + RTRIM(PS_DIST_LN.CHARTFIELD3) AS PH_REF_CHAR_04,
'Type: ' + PS_DIST_LN.DISTRIBUTION_TYPE + '-' + PS_DIST_LN.TRANS_TYPE + '/' + PS_DIST_LN.CATEGORY AS PH_REF_CHAR_05,
RTRIM(PS_DIST_LN.APPL_JRNL_ID) AS PH_REF_CHAR_06
FROM PHSAPSD4.FS84TST.dbo.PS_DIST_LN PS_DIST_LN LEFT JOIN PHSAPSD4.FS84TST.dbo.PS_ASSET PS_ASSET
ON PS_DIST_LN.BUSINESS_UNIT = PS_ASSET.BUSINESS_UNIT
AND PS_DIST_LN.ASSET_ID = PS_ASSET.ASSET_ID*/




GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

CREATE VIEW dbo.qryAPDetails
AS
SELECT   VAL.MONETARY_AMOUNT, VAL.STATISTIC_AMOUNT, VAL.GL_DISTRIB_STATUS, VAL.JOURNAL_ID, VAL.JOURNAL_LINE, VAL.JRNL_LN_REF, 
                      VL.PO_ID AS PH_REF_CHAR_01, ISNULL('Grp:' + RTRIM(VCHR.GRP_AP_ID),'') + '-Vchr:' + VAL.VOUCHER_ID AS PH_REF_CHAR_02, 
                      left('Inv:' + RTRIM(VCHR.INVOICE_ID),14) + '-Vndr:' + VL.VENDOR_ID  AS PH_REF_CHAR_03, VNDR.NAME1 AS PH_REF_CHAR_04, 
                      VAL.DESCR AS PH_REF_CHAR_05, VL.DESCR AS PH_REF_CHAR_06
FROM         PHSAPSD4.FS84TST.dbo.PS_VOUCHER_LINE VL LEFT OUTER JOIN
                      PHSAPSD4.FS84TST.dbo.PS_VENDOR VNDR ON VL.VENDOR_ID = VNDR.VENDOR_ID LEFT OUTER JOIN
                      PHSAPSD4.FS84TST.dbo.PS_VOUCHER VCHR ON VL.VOUCHER_ID = VCHR.VOUCHER_ID AND 
                      VL.BUSINESS_UNIT = VCHR.BUSINESS_UNIT RIGHT OUTER JOIN
                      PHSAPSD4.FS84TST.dbo.PS_VCHR_ACCTG_LINE VAL ON VL.BUSINESS_UNIT = VAL.BUSINESS_UNIT AND 
                      VL.VOUCHER_ID = VAL.VOUCHER_ID AND VL.VOUCHER_LINE_NUM = VAL.VOUCHER_LINE_NUM
/* 20040817
SELECT     VAL.MONETARY_AMOUNT, 
	         VAL.STATISTIC_AMOUNT, 
                      VAL.GL_DISTRIB_STATUS, 
                      VAL.JOURNAL_ID, VAL.JOURNAL_LINE, 
                      VAL.JRNL_LN_REF, VL.PO_ID AS PH_REF_CHAR_01, 
                      'Grp:' + RTRIM(VCHR.GRP_AP_ID) + '-Vchr:' + VAL.VOUCHER_ID AS PH_REF_CHAR_02, 
                      'Inv:' + RTRIM(VCHR.INVOICE_ID)  + '-Vndr:' + VL.VENDOR_ID AS PH_REF_CHAR_03, 
                      VNDR.NAME1 AS PH_REF_CHAR_04, 
                      VAL.DESCR AS PH_REF_CHAR_05, 
                      VL.DESCR AS PH_REF_CHAR_06
FROM         PHSAPSD4.FS84TST.dbo.PS_VOUCHER_LINE VL INNER JOIN
                      PHSAPSD4.FS84TST.dbo.PS_VCHR_ACCTG_LINE VAL ON VL.BUSINESS_UNIT = VAL.BUSINESS_UNIT AND 
                      VL.VOUCHER_ID = VAL.VOUCHER_ID AND 
                      VL.VOUCHER_LINE_NUM = VAL.VOUCHER_LINE_NUM INNER JOIN
                      PHSAPSD4.FS84TST.dbo.PS_VENDOR VNDR ON VL.VENDOR_ID = VNDR.VENDOR_ID INNER JOIN
                      PHSAPSD4.FS84TST.dbo.PS_VOUCHER VCHR ON VL.VOUCHER_ID = VCHR.VOUCHER_ID AND 
                      VL.BUSINESS_UNIT = VCHR.BUSINESS_UNIT
*/
/*
SELECT     dbo.PS_VCHR_ACCTG_LINE.MONETARY_AMOUNT, dbo.PS_VCHR_ACCTG_LINE.STATISTIC_AMOUNT, 
                      dbo.PS_VCHR_ACCTG_LINE.GL_DISTRIB_STATUS, dbo.PS_VCHR_ACCTG_LINE.JOURNAL_ID, dbo.PS_VCHR_ACCTG_LINE.JOURNAL_LINE, 
                      dbo.PS_VCHR_ACCTG_LINE.JRNL_LN_REF, dbo.PS_VOUCHER_LINE.PO_ID AS PH_REF_CHAR_01, 'Grp:' + RTRIM(dbo.PS_VOUCHER.GRP_AP_ID) 
                      + '-Vchr:' + dbo.PS_VCHR_ACCTG_LINE.VOUCHER_ID AS PH_REF_CHAR_02, 'Inv:' + RTRIM(dbo.PS_VOUCHER.INVOICE_ID) 
                      + '-Vndr:' + dbo.PS_VOUCHER_LINE.VENDOR_ID AS PH_REF_CHAR_03, dbo.PS_VENDOR.NAME1 AS PH_REF_CHAR_04, 
                      dbo.PS_VCHR_ACCTG_LINE.DESCR AS PH_REF_CHAR_05, dbo.PS_VOUCHER_LINE.DESCR AS PH_REF_CHAR_06
FROM         dbo.PS_VOUCHER_LINE INNER JOIN
                      dbo.PS_VCHR_ACCTG_LINE ON dbo.PS_VOUCHER_LINE.BUSINESS_UNIT = dbo.PS_VCHR_ACCTG_LINE.BUSINESS_UNIT AND 
                      dbo.PS_VOUCHER_LINE.VOUCHER_ID = dbo.PS_VCHR_ACCTG_LINE.VOUCHER_ID AND 
                      dbo.PS_VOUCHER_LINE.VOUCHER_LINE_NUM = dbo.PS_VCHR_ACCTG_LINE.VOUCHER_LINE_NUM INNER JOIN
                      dbo.PS_VENDOR ON dbo.PS_VOUCHER_LINE.VENDOR_ID = dbo.PS_VENDOR.VENDOR_ID INNER JOIN
                      dbo.PS_VOUCHER ON dbo.PS_VOUCHER_LINE.VOUCHER_ID = dbo.PS_VOUCHER.VOUCHER_ID AND 
                      dbo.PS_VOUCHER_LINE.BUSINESS_UNIT = dbo.PS_VOUCHER.BUSINESS_UNIT

*/








GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO


CREATE  VIEW dbo.qryDetailSourceCombinations
AS
SELECT DISTINCT hdr.ACCTG_DEF_NAME, ln.JRNL_LINE_SOURCE, hdr.SOURCE
FROM         dbo.PS_JRNL_HEADER hdr INNER JOIN
                      dbo.PS_JRNL_LN ln ON hdr.JOURNAL_ID = ln.JOURNAL_ID


GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO


CREATE  VIEW dbo.qryDistinctDetailSources
AS
SELECT DISTINCT hdr.ACCTG_DEF_NAME, ln.JRNL_LINE_SOURCE
FROM         dbo.PS_JRNL_HEADER hdr INNER JOIN
                      dbo.PS_JRNL_LN ln ON hdr.JOURNAL_ID = ln.JOURNAL_ID
WHERE hdr.ACCTG_DEF_NAME > ''

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

CREATE VIEW dbo.qryIFXDetails
AS
SELECT 
	MONETARY_AMOUNT,
	STATISTIC_AMOUNT,
	GL_DISTRIB_STATUS,
	JOURNAL_ID,
	JOURNAL_LINE,
	JRNL_LN_REF,
	--JRNL_DESCR,
	PH_REF_CHAR_01,
	PH_REF_CHAR_02,
	PH_REF_CHAR_03,
	PH_REF_CHAR_04,
	PH_REF_CHAR_05,
	PH_REF_CHAR_06
FROM	PHSAPSD4.FS84TST.dbo.PS_PH_ACCTG_IF_AM
UNION ALL
SELECT 
	MONETARY_AMOUNT,
	STATISTIC_AMOUNT,
	GL_DISTRIB_STATUS,
	JOURNAL_ID,
	JOURNAL_LINE,
	JRNL_LN_REF,
	--JRNL_DESCR,
	PH_REF_CHAR_01,
	PH_REF_CHAR_02,
	PH_REF_CHAR_03,
	PH_REF_CHAR_04,
	PH_REF_CHAR_05,
	PH_REF_CHAR_06
FROM	PHSAPSD4.FS84TST.dbo.PS_PH_ACCTG_IF_AR
UNION ALL
SELECT 
	MONETARY_AMOUNT,
	STATISTIC_AMOUNT,
	GL_DISTRIB_STATUS,
	JOURNAL_ID,
	JOURNAL_LINE,
	JRNL_LN_REF,
	--JRNL_DESCR,
	PH_REF_CHAR_01,
	PH_REF_CHAR_02,
	PH_REF_CHAR_03,
	PH_REF_CHAR_04,
	PH_REF_CHAR_05,
	PH_REF_CHAR_06
FROM	PHSAPSD4.FS84TST.dbo.PS_PH_ACCTG_IF_INV
UNION ALL
SELECT 
	MONETARY_AMOUNT,
	STATISTIC_AMOUNT,
	GL_DISTRIB_STATUS,
	JOURNAL_ID,
	JOURNAL_LINE,
	JRNL_LN_REF,
	--JRNL_DESCR,
	PH_REF_CHAR_01,
	PH_REF_CHAR_02,
	PH_REF_CHAR_03,
	PH_REF_CHAR_04,
	PH_REF_CHAR_05,
	PH_REF_CHAR_06
FROM	PHSAPSD4.FS84TST.dbo.PS_PH_ACCTG_IF_MI
UNION ALL
SELECT 
	ifpy.MONETARY_AMOUNT,
	ifpy.STATISTIC_AMOUNT,
	ifpy.GL_DISTRIB_STATUS,
	ifpy.JOURNAL_ID,
	ifpy.JOURNAL_LINE,
	ifpy.JRNL_LN_REF,
	--JRNL_DESCR,
	ifpy.PH_REF_CHAR_01,
	ifpy.PH_REF_CHAR_02,
	ifpy.PH_REF_CHAR_03,
	ifpy.PH_REF_CHAR_04,
	ifpy.PH_REF_CHAR_05,
	ifpy.PH_REF_CHAR_06
FROM	PHSAPSD4.FS84TST.dbo.PS_PH_ACCTG_IF_PY ifpy

-- added linked srvr table  20040213







GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

CREATE VIEW dbo.qryINDetails
AS
SELECT
SC.MONETARY_AMOUNT,
SC.STATISTIC_AMOUNT,
SC.GL_DISTRIB_STATUS,
SC.JOURNAL_ID,
SC.JOURNAL_LINE,
SC.JRNL_LN_REF,
SC.BUSINESS_UNIT_GL ,
SC.FISCAL_YEAR ,
SC.ACCOUNTING_PERIOD,
--SC.UNIT_MEASURE_STD AS PH_REF_CHAR_01,
TRN.PO_ID AS PH_REF_CHAR_01,
'Order/Recv:' + RTRIM(SC.ORDER_NO) + ' ' + SC.RECEIVER_ID AS PH_REF_CHAR_02,
'Date:' + convert(char(10),ACCOUNTING_DT,101) AS PH_REF_CHAR_03,
'ItmID:' + RTRIM(SC.INV_ITEM_ID) + ' Qty:' + CONVERT(varchar(15),convert(decimal(18,2),TRN.QTY)) + ' ' + SC.UNIT_MEASURE_STD AS PH_REF_CHAR_04,
ITM.DESCR AS PH_REF_CHAR_05,
'CAT: ' + ITM.CATEGORY_ID + '-' + CAT.DESCR AS PH_REF_CHAR_06
FROM
PHSAPSD4.FS84TST.dbo.PS_CM_ACCTG_LINE SC LEFT OUTER JOIN
PHSAPSD4.FS84TST.dbo.PS_MASTER_ITEM_TBL ITM ON 
SC.INV_ITEM_ID = ITM.INV_ITEM_ID LEFT OUTER JOIN
PHSAPSD4.FS84TST.dbo.PS_ITM_CAT_TBL CAT ON
CAT.CATEGORY_ID = ITM.CATEGORY_ID AND
CAT.SETID = ITM.SETID 
LEFT OUTER JOIN PHSAPSD4.FS84TST.dbo.PS_TRANSACTION_INV TRN ON
SC.BUSINESS_UNIT = TRN.BUSINESS_UNIT AND 
SC.INV_ITEM_ID = TRN.INV_ITEM_ID AND 
SC.DT_TIMESTAMP = TRN.DT_TIMESTAMP AND 
SC.SEQ_NBR = TRN.SEQ_NBR
WHERE CAT.EFFDT = (SELECT MAX(C_ED.EFFDT)
                  FROM PHSAPSD4.FS84TST.dbo.PS_ITM_CAT_TBL C_ED
		  WHERE C_ED.CATEGORY_ID = CAT.CATEGORY_ID AND 
			C_ED.SETID = CAT.SETID)
/* 2005-01-13
SELECT
SC.MONETARY_AMOUNT,
SC.STATISTIC_AMOUNT,
SC.GL_DISTRIB_STATUS,
SC.JOURNAL_ID,
SC.JOURNAL_LINE,
SC.JRNL_LN_REF,
SC.BUSINESS_UNIT_GL ,
SC.FISCAL_YEAR ,
SC.ACCOUNTING_PERIOD,
SC.UNIT_MEASURE_STD AS PH_REF_CHAR_01,
'Order/Req:' + RTRIM(SC.ORDER_NO) + ' ' + SC.RECEIVER_ID AS PH_REF_CHAR_02,
'Date:' + convert(char(10),ACCOUNTING_DT,101) AS PH_REF_CHAR_03,
'ItemID: ' + SC.INV_ITEM_ID AS PH_REF_CHAR_04,
ITM.DESCR AS PH_REF_CHAR_05,
'CAT: ' + ITM.CATEGORY_ID + '-' + CAT.DESCR AS PH_REF_CHAR_06
FROM
PHSAPSD4.FS84TST.dbo.PS_CM_ACCTG_LINE SC LEFT OUTER JOIN
PHSAPSD4.FS84TST.dbo.PS_MASTER_ITEM_TBL ITM ON 
SC.INV_ITEM_ID = ITM.INV_ITEM_ID LEFT OUTER JOIN
PHSAPSD4.FS84TST.dbo.PS_ITM_CAT_TBL CAT ON
CAT.CATEGORY_ID = ITM.CATEGORY_ID AND
CAT.SETID = ITM.SETID
WHERE CAT.EFFDT = (SELECT MAX(C_ED.EFFDT)
                  FROM PHSAPSD4.FS84TST.dbo.PS_ITM_CAT_TBL C_ED
		  WHERE C_ED.CATEGORY_ID = CAT.CATEGORY_ID AND 
			C_ED.SETID = CAT.SETID)
*/











GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

CREATE VIEW dbo.qryJrnlDetails_APG
AS
SELECT     dbo.PS_JRNL_LN.BUSINESS_UNIT, dbo.PS_JRNL_HEADER.FISCAL_YEAR, dbo.PS_JRNL_HEADER.ACCOUNTING_PERIOD, 
                      dbo.PS_JRNL_HEADER.JOURNAL_ID, dbo.PS_JRNL_HEADER.JOURNAL_DATE, dbo.PS_JRNL_HEADER.REVERSAL_CD, 
                      dbo.PS_JRNL_LN.JOURNAL_LINE, dbo.PS_JRNL_LN.JRNL_LN_REF, dbo.PS_JRNL_HEADER.SOURCE, dbo.PS_JRNL_LN.ACCOUNT, 
                      dbo.PS_JRNL_LN.DEPTID, dbo.PS_JRNL_LN.OPERATING_UNIT, dbo.PS_JRNL_LN.FUND_CODE, dbo.PS_JRNL_LN.PROJECT_ID, 
                      dbo.PS_JRNL_LN.CHARTFIELD1, 
--Removed 2003/08/5		CASE WHEN PS_JRNL_HEADER.REVERSAL_CD = 'R' THEN dbo.PS_JRNL_LN.MONETARY_AMOUNT * -1 ELSE dbo.PS_JRNL_LN.MONETARY_AMOUNT END AS MONETARY_AMOUNT,
--Removed 2003/08/5		CASE WHEN PS_JRNL_HEADER.REVERSAL_CD = 'R' THEN dbo.PS_JRNL_LN.STATISTIC_AMOUNT * -1 ELSE dbo.PS_JRNL_LN.STATISTIC_AMOUNT END AS STATISTIC_AMOUNT, 
		dbo.PS_JRNL_LN.MONETARY_AMOUNT,
		dbo.PS_JRNL_LN.STATISTIC_AMOUNT, 
                      dbo.PS_JRNL_HEADER.JRNL_HDR_STATUS, dbo.PS_JRNL_LN.LINE_DESCR, dbo.qryAPDetails.JRNL_LN_REF AS JRNL_LN_REF2, 
                      dbo.qryAPDetails.PH_REF_CHAR_01, dbo.qryAPDetails.PH_REF_CHAR_02, dbo.qryAPDetails.PH_REF_CHAR_03, dbo.qryAPDetails.PH_REF_CHAR_04, 
                      dbo.qryAPDetails.PH_REF_CHAR_05, dbo.qryAPDetails.PH_REF_CHAR_06 ,
 
--Removed 2003/08/5		ISNULL(CASE WHEN PS_JRNL_HEADER.REVERSAL_CD = 'R' THEN qryAPDetails.MONETARY_AMOUNT * -1 ELSE qryAPDetails.MONETARY_AMOUNT END, CASE WHEN PS_JRNL_HEADER.REVERSAL_CD = 'R' THEN dbo.PS_JRNL_LN.MONETARY_AMOUNT * -1 ELSE dbo.PS_JRNL_LN.MONETARY_AMOUNT END) AS DET_AMT, 
--Removed 2003/08/5		ISNULL(CASE WHEN PS_JRNL_HEADER.REVERSAL_CD = 'R' THEN qryAPDetails.STATISTIC_AMOUNT * -1 ELSE qryAPDetails.STATISTIC_AMOUNT END, CASE WHEN PS_JRNL_HEADER.REVERSAL_CD = 'R' THEN dbo.PS_JRNL_LN.STATISTIC_AMOUNT * -1 ELSE dbo.PS_JRNL_LN.STATISTIC_AMOUNT END) AS DET_STAT_AMT
--Removed 2003/08/15		CASE WHEN dbo.qryAPDetails.MONETARY_AMOUNT<> dbo.PS_JRNL_LN.MONETARY_AMOUNT THEN	dbo.PS_JRNL_LN.MONETARY_AMOUNT
--Removed 2003/08/15		ELSE ISNULL(dbo.qryAPDetails.MONETARY_AMOUNT, dbo.PS_JRNL_LN.MONETARY_AMOUNT)  END AS  DET_AMT,
--Removed 2003/08/15		CASE WHEN dbo.qryAPDetails.STATISTIC_AMOUNT<> dbo.PS_JRNL_LN.STATISTIC_AMOUNT THEN	dbo.PS_JRNL_LN.STATISTIC_AMOUNT
--Removed 2003/08/15		ELSE ISNULL(dbo.qryAPDetails.STATISTIC_AMOUNT, dbo.PS_JRNL_LN.STATISTIC_AMOUNT) END  AS DET_STAT_AMT
ISNULL(dbo.qryAPDetails.MONETARY_AMOUNT, dbo.PS_JRNL_LN.MONETARY_AMOUNT)  AS  DET_AMT, 
ISNULL(dbo.qryAPDetails.STATISTIC_AMOUNT, dbo.PS_JRNL_LN.STATISTIC_AMOUNT)  AS DET_STAT_AMT
FROM         dbo.PS_JRNL_HEADER INNER JOIN
                      dbo.PS_JRNL_LN ON dbo.PS_JRNL_HEADER.JOURNAL_ID = dbo.PS_JRNL_LN.JOURNAL_ID AND 
                      dbo.PS_JRNL_HEADER.JOURNAL_DATE = dbo.PS_JRNL_LN.JOURNAL_DATE AND 

                      dbo.PS_JRNL_HEADER.BUSINESS_UNIT = dbo.PS_JRNL_LN.BUSINESS_UNIT  --added 2003/07/14

                      AND dbo.PS_JRNL_HEADER.UNPOST_SEQ = dbo.PS_JRNL_LN.UNPOST_SEQ --removed 2003/08/5
		LEFT OUTER JOIN
                      dbo.qryAPDetails ON dbo.PS_JRNL_LN.JOURNAL_ID = dbo.qryAPDetails.JOURNAL_ID COLLATE Latin1_General_BIN
						AND dbo.PS_JRNL_LN.JOURNAL_LINE = dbo.qryAPDetails.JOURNAL_LINE
WHERE     ((dbo.PS_JRNL_HEADER.JRNL_HDR_STATUS = 'P') OR
                      (dbo.PS_JRNL_HEADER.JRNL_HDR_STATUS = 'U')) AND
		(dbo.PS_JRNL_HEADER.SOURCE = 'APG') AND
			(dbo.PS_JRNL_LN.JRNL_LINE_STATUS <> 1)























GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

CREATE VIEW qryJrnlDetails_ING
AS
--2004-06-15
--Details from Inventory issues
SELECT     dbo.PS_JRNL_LN.BUSINESS_UNIT, dbo.PS_JRNL_HEADER.FISCAL_YEAR, dbo.PS_JRNL_HEADER.ACCOUNTING_PERIOD, 
                      dbo.PS_JRNL_HEADER.JOURNAL_ID, dbo.PS_JRNL_HEADER.JOURNAL_DATE, dbo.PS_JRNL_HEADER.REVERSAL_CD, 
                      dbo.PS_JRNL_LN.JOURNAL_LINE, dbo.PS_JRNL_LN.JRNL_LN_REF, dbo.PS_JRNL_HEADER.SOURCE, dbo.PS_JRNL_LN.ACCOUNT, 
                      dbo.PS_JRNL_LN.DEPTID, dbo.PS_JRNL_LN.OPERATING_UNIT, dbo.PS_JRNL_LN.FUND_CODE, dbo.PS_JRNL_LN.PROJECT_ID, 
                      dbo.PS_JRNL_LN.CHARTFIELD1, 
                      dbo.PS_JRNL_LN.MONETARY_AMOUNT,
                      dbo.PS_JRNL_LN.STATISTIC_AMOUNT, 
                      dbo.PS_JRNL_HEADER.JRNL_HDR_STATUS, dbo.PS_JRNL_LN.LINE_DESCR, dbo.qryINDetails.JRNL_LN_REF AS JRNL_LN_REF2, 
                      dbo.qryINDetails.PH_REF_CHAR_01, dbo.qryINDetails.PH_REF_CHAR_02, dbo.qryINDetails.PH_REF_CHAR_03, dbo.qryINDetails.PH_REF_CHAR_04, 
                      dbo.qryINDetails.PH_REF_CHAR_05, dbo.qryINDetails.PH_REF_CHAR_06 ,
                      ISNULL(dbo.qryINDetails.MONETARY_AMOUNT, dbo.PS_JRNL_LN.MONETARY_AMOUNT)  AS  DET_AMT, 
                      ISNULL(dbo.qryINDetails.STATISTIC_AMOUNT, dbo.PS_JRNL_LN.STATISTIC_AMOUNT)  AS DET_STAT_AMT
FROM         dbo.PS_JRNL_HEADER INNER JOIN
                      dbo.PS_JRNL_LN ON dbo.PS_JRNL_HEADER.JOURNAL_ID = dbo.PS_JRNL_LN.JOURNAL_ID AND 
                      dbo.PS_JRNL_HEADER.JOURNAL_DATE = dbo.PS_JRNL_LN.JOURNAL_DATE AND 
                      dbo.PS_JRNL_HEADER.BUSINESS_UNIT = dbo.PS_JRNL_LN.BUSINESS_UNIT
                      AND dbo.PS_JRNL_HEADER.UNPOST_SEQ = dbo.PS_JRNL_LN.UNPOST_SEQ
		LEFT OUTER JOIN
                      dbo.qryINDetails ON dbo.PS_JRNL_LN.JOURNAL_ID = dbo.qryINDetails.JOURNAL_ID COLLATE Latin1_General_BIN
						AND dbo.PS_JRNL_LN.JOURNAL_LINE = dbo.qryINDetails.JOURNAL_LINE
WHERE     ((dbo.PS_JRNL_HEADER.JRNL_HDR_STATUS = 'P') OR
                      (dbo.PS_JRNL_HEADER.JRNL_HDR_STATUS = 'U')) AND
                      (dbo.PS_JRNL_HEADER.SOURCE = 'ING') AND
			(dbo.PS_JRNL_LN.JRNL_LINE_STATUS <> 1)





GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

CREATE VIEW dbo.qryJrnlDetails_ONL
AS
SELECT     dbo.PS_JRNL_LN.BUSINESS_UNIT, dbo.PS_JRNL_HEADER.FISCAL_YEAR, dbo.PS_JRNL_HEADER.ACCOUNTING_PERIOD, 
                      dbo.PS_JRNL_HEADER.JOURNAL_ID, dbo.PS_JRNL_HEADER.JOURNAL_DATE, dbo.PS_JRNL_LN.JOURNAL_LINE, dbo.PS_JRNL_LN.JRNL_LN_REF, 
                      dbo.PS_JRNL_HEADER.SOURCE, dbo.PS_JRNL_LN.ACCOUNT, dbo.PS_JRNL_LN.DEPTID, dbo.PS_JRNL_LN.OPERATING_UNIT, 
                      dbo.PS_JRNL_LN.FUND_CODE, dbo.PS_JRNL_LN.PROJECT_ID, dbo.PS_JRNL_LN.CHARTFIELD1, dbo.PS_JRNL_HEADER.REVERSAL_CD, 
                      dbo.PS_JRNL_LN.MONETARY_AMOUNT, dbo.PS_JRNL_LN.STATISTIC_AMOUNT, dbo.PS_JRNL_HEADER.JRNL_HDR_STATUS, 
                      dbo.PS_JRNL_LN.LINE_DESCR, '' AS JRNL_LN_REF2,  ''  AS PH_REF_CHAR_01, dbo.PS_JRNL_HEADER.DESCR AS PH_REF_CHAR_02, 
                      '' AS PH_REF_CHAR_03, '' AS PH_REF_CHAR_04, '' AS PH_REF_CHAR_05, '' AS PH_REF_CHAR_06, 
                      dbo.PS_JRNL_LN.MONETARY_AMOUNT AS DET_AMT, dbo.PS_JRNL_LN.STATISTIC_AMOUNT AS DET_STAT
FROM         dbo.PS_JRNL_HEADER INNER JOIN
                      dbo.PS_JRNL_LN ON dbo.PS_JRNL_HEADER.BUSINESS_UNIT = dbo.PS_JRNL_LN.BUSINESS_UNIT AND 
                      dbo.PS_JRNL_HEADER.JOURNAL_DATE = dbo.PS_JRNL_LN.JOURNAL_DATE AND 
                      dbo.PS_JRNL_HEADER.JOURNAL_ID = dbo.PS_JRNL_LN.JOURNAL_ID
                     AND dbo.PS_JRNL_HEADER.UNPOST_SEQ = dbo.PS_JRNL_LN.UNPOST_SEQ --removed 2003/08/5

WHERE     (dbo.PS_JRNL_HEADER.JRNL_HDR_STATUS = 'P' OR
                      dbo.PS_JRNL_HEADER.JRNL_HDR_STATUS = 'U') AND (dbo.PS_JRNL_HEADER.SOURCE NOT IN ('APG', 'PYG', 'IFX','AMG','ING','PO')) AND
			(dbo.PS_JRNL_LN.JRNL_LINE_STATUS <> 1)
-- 2004/01/31 ADDED 'AMG' IN THE NOT IN LIST
-- REMEBER TO MAKE CHANGES IN THE STORED PROCEDURE, THAT'S WHAT IS USED FOR EXTRACTING DATA







GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO


SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

CREATE View dbo.qryPODetails
AS
SELECT 
R.MONETARY_AMOUNT,
R.STATISTIC_AMOUNT,
R.GL_DISTRIB_STATUS,
R.JOURNAL_ID,
R.JOURNAL_LINE,
R.JRNL_LN_REF,
R.BUSINESS_UNIT_GL ,
R.FISCAL_YEAR ,
R.ACCOUNTING_PERIOD,
'PO Accrual' AS PH_REF_CHAR_01,
'PO:' + R.PO_ID + '-' + CONVERT(VARCHAR(10), R.LINE_NBR) AS PH_REF_CHAR_02,
LEFT(DESCR254_MIXED,25) AS PH_REF_CHAR_03,
SUBSTRING(DESCR254_MIXED,26,25) AS PH_REF_CHAR_04,
SUBSTRING(DESCR254_MIXED,51,25) AS PH_REF_CHAR_05,
SUBSTRING(DESCR254_MIXED,76,80) AS PH_REF_CHAR_06
FROM
PHSAPSD4.FS84TST.dbo.PS_RECV_LN_ACCTG R
LEFT OUTER JOIN PHSAPSD4.FS84TST.dbo.PS_PO_LINE PL
ON R.BUSINESS_UNIT_PO = PL.BUSINESS_UNIT
AND R.PO_ID = PL.PO_ID
AND R.LINE_NBR = PL.LINE_NBR











GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

CREATE VIEW dbo.qryPYDetails
AS
SELECT     ln.MONETARY_AMOUNT, ln.STATISTIC_AMOUNT, ln.GL_DISTRIB_STATUS, 
                      ln.JOURNAL_ID, ln.JOURNAL_LINE, ln.JRNL_LN_REF, CONVERT(CHAR(10), 
                      ln.JOURNAL_DATE, 101) AS PH_REF_CHAR_01, ln.CHARTFIELD2 AS PH_REF_CHAR_02, 
                      ln.LINE_DESCR AS PH_REF_CHAR_03, ISNULL(pd.[NAME],'') AS PH_REF_CHAR_04, 
                       ln.CHARTFIELD3 AS PH_REF_CHAR_05, '' AS PH_REF_CHAR_06
FROM         PHSAPSD4.FS84TST.dbo.PS_HR_ACCTG_LINE ln LEFT OUTER JOIN
                      PHSAPSD4.FS84TST.dbo.PS_PERSONAL_DATA pd ON ln.JRNL_LN_REF = pd.EMPLID

/*Old 20040212

SELECT     dbo.PS_HR_ACCTG_LINE.MONETARY_AMOUNT, dbo.PS_HR_ACCTG_LINE.STATISTIC_AMOUNT, dbo.PS_HR_ACCTG_LINE.GL_DISTRIB_STATUS, 
                      dbo.PS_HR_ACCTG_LINE.JOURNAL_ID, dbo.PS_HR_ACCTG_LINE.JOURNAL_LINE, dbo.PS_HR_ACCTG_LINE.JRNL_LN_REF, CONVERT(CHAR(10), 
                      dbo.PS_HR_ACCTG_LINE.JOURNAL_DATE, 101) AS PH_REF_CHAR_01, dbo.PS_HR_ACCTG_LINE.CHARTFIELD2 AS PH_REF_CHAR_02, 
                      dbo.PS_HR_ACCTG_LINE.LINE_DESCR AS PH_REF_CHAR_03, ISNULL(dbo.PS_PERSONAL_DATA.NAME,'') AS PH_REF_CHAR_04, 
                       dbo.PS_HR_ACCTG_LINE.CHARTFIELD3 AS PH_REF_CHAR_05, '' AS PH_REF_CHAR_06
FROM         dbo.PS_HR_ACCTG_LINE LEFT OUTER JOIN
                      dbo.PS_PERSONAL_DATA ON dbo.PS_HR_ACCTG_LINE.JRNL_LN_REF = dbo.PS_PERSONAL_DATA.EMPLID


*/






GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO


SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO


/****** Object:  View dbo.PS_VCHR_ACCT_DRILL    Script Date: 5/21/2003 10:48:33 PM ******/
CREATE VIEW PS_VCHR_ACCT_DRILL (BUSINESS_UNIT, JOURNAL_ID, JOURNAL_DATE, JOURNAL_LINE, BUSINESS_UNIT_GL, VOUCHER_ID, UNPOST_SEQ, APPL_JRNL_ID, PYMNT_CNT, VOUCHER_LINE_NUM, DISTRIB_LINE_NUM, DST_ACCT_TYPE, CF_BAL_LINE_NUM, LEDGER, ACCOUNT, DEPTID, STATISTICS_CODE, FOREIGN_AMOUNT, FOREIGN_CURRENCY, RT_TYPE, RATE_MULT, RATE_DIV, MONETARY_AMOUNT, QTY_VCHR, STATISTIC_AMOUNT, JRNL_LN_REF, DESCR, MERCHANDISE_AMT, MERCH_AMT_BSE, DSCNT_AMT_BSE, SALETX_AMT_BSE, USETAX_AMT_BSE, VAT_INV_AMT_BSE, VAT_NONINV_AMT_BSE, VAT_RCVRY_AMT_BSE, FREIGHT_AMT_BSE, CHART_EDIT_STATUS, ACCOUNTING_DT, ACCOUNTING_PERIOD, FISCAL_YEAR, MOVEMENT_FLAG, GL_DISTRIB_STATUS, PROCESS_INSTANCE, ERROR_FLAG, FINAL_REF_IND, REFERENCE_NUMBER, REF_CLOSED, REF_DIST_LINE, REF_LINE_NUMBER, BUSINESS_UNIT_PO, PO_ID, LINE_NBR, SCHED_NBR, PO_DIST_LINE_NUM, BCM_LINE_STATUS, BCM_POST_AMOUNT, BCM_POST_AMT_TOT, BUSINESS_UNIT_PC, ACTIVITY_ID, ANALYSIS_TYPE, RESOURCE_TYPE, RESOURCE_CATEGORY, RESOURCE_SUB_CAT, PC_DISTRIB_STATUS, CURRENCY_CD, ASSET_FLG, BUSINESS_UNIT_AM, ASSET_ID, PROFILE_ID, AM_DISTRIB_STATUS, VAT_DISTRIB_STATUS, BUSINESS_UNIT_RECV, RECEIVER_ID, RECV_LN_NBR, RECV_SHIP_SEQ_NBR, RECV_DIST_LINE_NUM, LEDGER_GROUP, VAT_TXN_TYPE_CD, FREIGHT_AMT, SALETX_AMT, USETAX_AMT, VAT_INV_AMT, VAT_NONINV_AMT, DSCNT_AMT, VAT_RECOVERY_PCT, VAT_BASIS_AMT, VAT_BASIS_AMT_BSE, VAT_CALC_AMT, VAT_CALC_AMT_BSE, VAT_RCVRY_AMT, VAT_DSCNT_ADJ, VAT_DSCNT_ADJ_BSE, VAT_DSCNT_RCVRY, VAT_DSCNT_RCVR_BSE, TAX_CD_VAT, TAX_CD_VAT_PCT, VAT_DCLRTN_DT, OPERATING_UNIT, PRODUCT, FUND_CODE, CLASS_FLD, PROGRAM_CODE, BUDGET_REF, AFFILIATE, AFFILIATE_INTRA1, AFFILIATE_INTRA2, CHARTFIELD1, CHARTFIELD2, CHARTFIELD3, PROJECT_ID, VAT_APPLICABILITY, VAT_REBATE_PCT, VAT_REBATE_AMT, VAT_REBATE_AMT_BSE, VAT_USE_ID, VAT_ENTITY, SHIPTO_ID, SUT_BASE_ID, TAX_CD_SUT, TAX_CD_SUT_PCT, SUT_APPLICABILITY, DOC_TYPE, DOC_SEQ_DATE, DOC_SEQ_NBR, DOC_SEQ_STATUS, POSTING_DATE, IST_DISTRIB_STATUS) AS SELECT A.BUSINESS_UNIT_GL ,A.JOURNAL_ID ,A.JOURNAL_DATE ,A.JOURNAL_LINE ,A.BUSINESS_UNIT ,A.VOUCHER_ID ,A.UNPOST_SEQ ,A.APPL_JRNL_ID ,A.PYMNT_CNT ,A.VOUCHER_LINE_NUM ,A.DISTRIB_LINE_NUM ,A.DST_ACCT_TYPE ,A.CF_BAL_LINE_NUM ,A.LEDGER ,A.ACCOUNT , A.DEPTID ,A.STATISTICS_CODE ,A.FOREIGN_AMOUNT ,A.FOREIGN_CURRENCY ,A.RT_TYPE ,A.RATE_MULT ,A.RATE_DIV ,A.MONETARY_AMOUNT ,A.QTY_VCHR ,A.STATISTIC_AMOUNT ,A.JRNL_LN_REF ,A.DESCR ,A.MERCHANDISE_AMT ,A.MERCH_AMT_BSE ,A.DSCNT_AMT_BSE ,A.SALETX_AMT_BSE ,A.USETAX_AMT_BSE ,A.VAT_INV_AMT_BSE ,A.VAT_NONINV_AMT_BSE ,A.VAT_RCVRY_AMT_BSE ,A.FREIGHT_AMT_BSE ,A.CHART_EDIT_STATUS ,A.ACCOUNTING_DT ,A.ACCOUNTING_PERIOD ,A.FISCAL_YEAR ,A.MOVEMENT_FLAG ,A.GL_DISTRIB_STATUS ,A.PROCESS_INSTANCE ,A.ERROR_FLAG ,A.FINAL_REF_IND ,A.REFERENCE_NUMBER ,A.REF_CLOSED ,A.REF_DIST_LINE ,A.REF_LINE_NUMBER ,A.BUSINESS_UNIT_PO ,A.PO_ID ,A.LINE_NBR ,A.SCHED_NBR ,A.PO_DIST_LINE_NUM ,A.BCM_LINE_STATUS ,A.BCM_POST_AMOUNT ,A.BCM_POST_AMT_TOT ,A.BUSINESS_UNIT_PC ,A.ACTIVITY_ID ,A.ANALYSIS_TYPE ,A.RESOURCE_TYPE ,A.RESOURCE_CATEGORY ,A.RESOURCE_SUB_CAT ,A.PC_DISTRIB_STATUS ,A.CURRENCY_CD ,A.ASSET_FLG ,A.BUSINESS_UNIT_AM ,A.ASSET_ID ,A.PROFILE_ID ,A.AM_DISTRIB_STATUS ,A.VAT_DISTRIB_STATUS ,A.BUSINESS_UNIT_RECV ,A.RECEIVER_ID ,A.RECV_LN_NBR ,A.RECV_SHIP_SEQ_NBR ,A.RECV_DIST_LINE_NUM ,A.LEDGER_GROUP ,A.VAT_TXN_TYPE_CD ,A.FREIGHT_AMT ,A.SALETX_AMT ,A.USETAX_AMT ,A.VAT_INV_AMT ,A.VAT_NONINV_AMT ,A.DSCNT_AMT ,A.VAT_RECOVERY_PCT ,A.VAT_BASIS_AMT ,A.VAT_BASIS_AMT_BSE ,A.VAT_CALC_AMT ,A.VAT_CALC_AMT_BSE ,A.VAT_RCVRY_AMT ,A.VAT_DSCNT_ADJ ,A.VAT_DSCNT_ADJ_BSE ,A.VAT_DSCNT_RCVRY ,A.VAT_DSCNT_RCVR_BSE ,A.TAX_CD_VAT ,A.TAX_CD_VAT_PCT ,A.VAT_DCLRTN_DT ,A.OPERATING_UNIT, A.PRODUCT, A.FUND_CODE, A.CLASS_FLD, A.PROGRAM_CODE, A.BUDGET_REF, A.AFFILIATE, A.AFFILIATE_INTRA1, A.AFFILIATE_INTRA2, A.CHARTFIELD1, A.CHARTFIELD2, A.CHARTFIELD3 ,A.PROJECT_ID ,VAT_APPLICABILITY ,A.VAT_REBATE_PCT ,A.VAT_REBATE_AMT ,A.VAT_REBATE_AMT_BSE ,A.VAT_USE_ID ,A.VAT_ENTITY ,A.SHIPTO_ID ,A.SUT_BASE_ID ,A.TAX_CD_SUT ,A.TAX_CD_SUT_PCT ,A.SUT_APPLICABILITY ,A.DOC_TYPE ,A.DOC_SEQ_DATE ,A.DOC_SEQ_NBR ,A.DOC_SEQ_STATUS ,A.POSTING_DATE ,A.IST_DISTRIB_STATUS FROM PS_VCHR_ACCTG_LINE A

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO


/****** Object:  View dbo.PS_VCHR_JRNL_VW    Script Date: 5/21/2003 10:48:33 PM ******/
CREATE VIEW PS_VCHR_JRNL_VW (BUSINESS_UNIT, VOUCHER_ID, INVOICE_ID, GROSS_AMT, SETID, VENDOR_NAME_SHORT, VENDOR_ID, NAME1, VOUCHER_ID_RELATED, TXN_CURRENCY_CD) AS SELECT A.BUSINESS_UNIT, A.VOUCHER_ID, A.INVOICE_ID, A.GROSS_AMT, A.VENDOR_SETID, B.VENDOR_NAME_SHORT, A.VENDOR_ID, B.NAME1, A.VOUCHER_ID_RELATED, A.TXN_CURRENCY_CD FROM PS_VOUCHER A, PS_VENDOR B WHERE A.VENDOR_SETID = B.SETID AND A.VENDOR_ID = B.VENDOR_ID AND A.VOUCHER_ID_RELATED <> ' ' AND A.VOUCHER_TYPE='J' AND A.ENTRY_STATUS <> 'X'

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO


/****** Object:  View dbo.qryApplicationSettings_BlankRecordKeys    Script Date: 6/2/2003 5:59:48 PM ******/

/****** Object:  View dbo.qryApplicationSettings_BlankRecordKey    Script Date: 6/2/2003 4:48:01 PM ******/



CREATE   VIEW qryApplicationSettings_BlankRecordKeys
AS 
	SELECT * FROM dbo.tblApplicationSettings
	WHERE [Key] LIKE '%[_]BlankRecordKey'





GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO


/****** Object:  View dbo.qryApplicationSettings_CurrentProfileSpecificSettings    Script Date: 6/2/2003 5:59:48 PM ******/


/****** Object:  View dbo.qryApplicationSettings_BlankRecordKey    Script Date: 6/2/2003 4:48:01 PM ******/



CREATE   VIEW qryApplicationSettings_CurrentProfileSpecificSettings
AS 
	SELECT ap.* 
	FROM dbo.tblApplicationSettings ap
		INNER JOIN (SELECT CONVERT(int, [Value]) AS CurrentProfile
				FROM dbo.tblApplicationSettings
				WHERE [Profile] IS NULL 
					AND [Key] = 'CurrentProfile') cp
		ON ap.[Profile] = cp.CurrentProfile







GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO


/****** Object:  View dbo.qryApplicationSettings_DtsLoadSimpleTables    Script Date: 6/2/2003 5:59:48 PM ******/

/****** Object:  View dbo.qryApplicationSettings_DtsLoadSimpleTables    Script Date: 6/2/2003 4:48:02 PM ******/



CREATE   VIEW qryApplicationSettings_DtsLoadSimpleTables
AS 
	SELECT * FROM dbo.tblApplicationSettings
	WHERE [Key] LIKE '%LoadSimpleTables[_]%'





GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO


/****** Object:  View dbo.qryApplicationSettings_Errors    Script Date: 6/2/2003 5:59:48 PM ******/

/****** Object:  View dbo.qryApplicationSettings_Errors    Script Date: 6/2/2003 4:48:02 PM ******/




CREATE   VIEW qryApplicationSettings_Errors
AS 
	SELECT [Profile], 
		CONVERT(varchar(256),[Key]) AS [Key], 
		[Value], 
		[Description] 
	FROM dbo.tblApplicationSettings
	WHERE [Key] LIKE '%[_]Errors[_]%'




GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO


/****** Object:  View dbo.qryApplicationSettings_Filters    Script Date: 6/2/2003 5:59:48 PM ******/

/****** Object:  View dbo.qryApplicationSettings_Filters    Script Date: 6/2/2003 4:48:02 PM ******/


CREATE  VIEW qryApplicationSettings_Filters
AS 
	SELECT * FROM dbo.tblApplicationSettings
	WHERE [Key] LIKE 'FilterFor%'




GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO


/****** Object:  View dbo.qryApplicationSettings_Scripts    Script Date: 6/2/2003 5:59:48 PM ******/

/****** Object:  View dbo.qryApplicationSettings_Scripts    Script Date: 6/2/2003 4:48:02 PM ******/


CREATE  VIEW qryApplicationSettings_Scripts
AS 
	SELECT * FROM dbo.tblApplicationSettings
	WHERE [Key] LIKE 'Script%'




GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO


/****** Object:  View dbo.qryApplicationSettings_ServersAndDatabases    Script Date: 6/2/2003 5:59:48 PM ******/

/****** Object:  View dbo.qryApplicationSettings_ServersAndDatabases    Script Date: 6/2/2003 4:48:02 PM ******/


CREATE  VIEW qryApplicationSettings_ServersAndDatabases
AS 
	SELECT * FROM dbo.tblApplicationSettings
	WHERE [Key] LIKE '%Server' 
		OR [Key] LIKE '%Database' 




GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO


/****** Object:  View dbo.qryApplicationSettings_Statistics    Script Date: 6/2/2003 5:59:48 PM ******/

/****** Object:  View dbo.qryApplicationSettings_Statistics    Script Date: 6/2/2003 4:48:02 PM ******/



CREATE   VIEW qryApplicationSettings_Statistics
AS 
	SELECT [Profile], 
		CONVERT(varchar(256),[Key]) AS [Key], 
		[Value], 
		[Description] 
	FROM dbo.tblApplicationSettings
	WHERE [Key] LIKE '%[_]Stats[_]%'



GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO


/****** Object:  View dbo.qryApplicationSettings_TruncateSettings    Script Date: 6/2/2003 5:59:48 PM ******/

/****** Object:  View dbo.qryApplicationSettings_TruncateSettings    Script Date: 6/2/2003 4:48:02 PM ******/




CREATE    VIEW qryApplicationSettings_TruncateSettings
	([Profile], [Key], [Value], [Description])
AS 
	SELECT [Profile], [Key], [Value], [Description]
	FROM dbo.tblApplicationSettings
	WHERE [Key] = 'AllTablesTruncateAndReloadRecordsOnNextImport'
		OR [Key] LIKE '%[_]TruncateTableOnLoad'






GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

CREATE VIEW dbo.qryDetailSourceLookups_MissingDetailSourceNames
AS
SELECT     *
FROM         dbo.tblDetailSourceLookups
WHERE     (DetailSourceName IS NULL) AND (NoDetailSource = 0)

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

--  do not delete
-- this returns lines from the common accounting interface tables.
CREATE VIEW dbo.qryDetails
AS
/*
--c&w conversion
SELECT 
	MONETARY_AMOUNT,
	GL_DISTRIB_STATUS,
	JOURNAL_ID,
	JOURNAL_LINE,
	JRNL_LN_REF,
	--JRNL_DESCR,
	PH_REF_CHAR_01,
	PH_REF_CHAR_02,
	PH_REF_CHAR_03,
	PH_REF_CHAR_04, -- THIS IS IMPORTANT
	PH_REF_CHAR_05,
	PH_REF_CHAR_06
FROM	PS_PH_ACCTG_CNV_CW
UNION
--bcca conversion
SELECT 
	MONETARY_AMOUNT,
	GL_DISTRIB_STATUS,
	JOURNAL_ID,
	JOURNAL_LINE,
	JRNL_LN_REF,
	--JRNL_DESCR,
	PH_REF_CHAR_01,
	PH_REF_CHAR_02,
	PH_REF_CHAR_03,
	PH_REF_CHAR_04,
	PH_REF_CHAR_05,
	PH_REF_CHAR_06
FROM	PS_PH_ACCTG_CNV_CA
UNION
--other conversion
SELECT 
	MONETARY_AMOUNT,
	GL_DISTRIB_STATUS,
	JOURNAL_ID,
	JOURNAL_LINE,
	JRNL_LN_REF,
	--JRNL_DESCR,
	PH_REF_CHAR_01,
	PH_REF_CHAR_02,
	PH_REF_CHAR_03,
	PH_REF_CHAR_04,
	PH_REF_CHAR_05,
	PH_REF_CHAR_06
FROM	PS_PH_ACCTG_CNV_MI
UNION
--mental hlth conversion
SELECT 
	MONETARY_AMOUNT,
	GL_DISTRIB_STATUS,
	JOURNAL_ID,
	JOURNAL_LINE,
	JRNL_LN_REF,
	--JRNL_DESCR,
	PH_REF_CHAR_01,
	PH_REF_CHAR_02,
	PH_REF_CHAR_03,
	PH_REF_CHAR_04,
	PH_REF_CHAR_05,
	PH_REF_CHAR_06
FROM	PS_PH_ACCTG_CNV_RF
UNION
*/

SELECT 
	MONETARY_AMOUNT,
	STATISTIC_AMOUNT,
	GL_DISTRIB_STATUS,
	JOURNAL_ID,
	JOURNAL_LINE,
	JRNL_LN_REF,
	--JRNL_DESCR,
	PH_REF_CHAR_01,
	PH_REF_CHAR_02,
	PH_REF_CHAR_03,
	PH_REF_CHAR_04,
	PH_REF_CHAR_05,
	PH_REF_CHAR_06
FROM	PS_PH_ACCTG_IF_AM
UNION
SELECT 
	MONETARY_AMOUNT,
	STATISTIC_AMOUNT,
	GL_DISTRIB_STATUS,
	JOURNAL_ID,
	JOURNAL_LINE,
	JRNL_LN_REF,
	--JRNL_DESCR,
	PH_REF_CHAR_01,
	PH_REF_CHAR_02,
	PH_REF_CHAR_03,
	PH_REF_CHAR_04,
	PH_REF_CHAR_05,
	PH_REF_CHAR_06
FROM	PS_PH_ACCTG_IF_AR
UNION
SELECT 
	MONETARY_AMOUNT,
	STATISTIC_AMOUNT,
	GL_DISTRIB_STATUS,
	JOURNAL_ID,
	JOURNAL_LINE,
	JRNL_LN_REF,
	--JRNL_DESCR,
	PH_REF_CHAR_01,
	PH_REF_CHAR_02,
	PH_REF_CHAR_03,
	PH_REF_CHAR_04,
	PH_REF_CHAR_05,
	PH_REF_CHAR_06
FROM	PS_PH_ACCTG_IF_INV
UNION
SELECT 
	MONETARY_AMOUNT,
	STATISTIC_AMOUNT,
	GL_DISTRIB_STATUS,
	JOURNAL_ID,
	JOURNAL_LINE,
	JRNL_LN_REF,
	--JRNL_DESCR,
	PH_REF_CHAR_01,
	PH_REF_CHAR_02,
	PH_REF_CHAR_03,
	PH_REF_CHAR_04,
	PH_REF_CHAR_05,
	PH_REF_CHAR_06
FROM	PS_PH_ACCTG_IF_MI
UNION
SELECT 
	MONETARY_AMOUNT,
	STATISTIC_AMOUNT,
	GL_DISTRIB_STATUS,
	JOURNAL_ID,
	JOURNAL_LINE,
	JRNL_LN_REF,
	--JRNL_DESCR,
	PH_REF_CHAR_01,
	PH_REF_CHAR_02,
	PH_REF_CHAR_03,
	PH_REF_CHAR_04,
	PH_REF_CHAR_05,
	PH_REF_CHAR_06
FROM	PS_PH_ACCTG_IF_PY
UNION
--AP
SELECT  
	PS_VCHR_ACCTG_LINE.MONETARY_AMOUNT, 
	PS_VCHR_ACCTG_LINE.STATISTIC_AMOUNT,
	PS_VCHR_ACCTG_LINE.GL_DISTRIB_STATUS,  
	PS_VCHR_ACCTG_LINE.JOURNAL_ID,
	PS_VCHR_ACCTG_LINE.JOURNAL_LINE, 
	PS_VCHR_ACCTG_LINE.JRNL_LN_REF, 
	PS_VOUCHER_LINE.PO_ID, 
	'Voucher: '+PS_VCHR_ACCTG_LINE.VOUCHER_ID, 
	'Vendor: '+PS_VOUCHER_LINE.VENDOR_ID, 
	PS_VENDOR.NAME1,
	PS_VCHR_ACCTG_LINE.DESCR, 
	PS_VOUCHER_LINE.DESCR
FROM         dbo.PS_VOUCHER_LINE INNER JOIN
                      dbo.PS_VCHR_ACCTG_LINE ON dbo.PS_VOUCHER_LINE.BUSINESS_UNIT = dbo.PS_VCHR_ACCTG_LINE.BUSINESS_UNIT AND 
                      dbo.PS_VOUCHER_LINE.VOUCHER_ID = dbo.PS_VCHR_ACCTG_LINE.VOUCHER_ID AND 
                      dbo.PS_VOUCHER_LINE.VOUCHER_LINE_NUM = dbo.PS_VCHR_ACCTG_LINE.VOUCHER_LINE_NUM INNER JOIN
                      dbo.PS_VENDOR ON dbo.PS_VOUCHER_LINE.VENDOR_ID = dbo.PS_VENDOR.VENDOR_ID
UNION
--PY
SELECT 
	PS_HR_ACCTG_LINE.MONETARY_AMOUNT, 
	PS_HR_ACCTG_LINE.STATISTIC_AMOUNT,
	PS_HR_ACCTG_LINE.GL_DISTRIB_STATUS, 
	PS_HR_ACCTG_LINE.JOURNAL_ID, 
	PS_HR_ACCTG_LINE.JOURNAL_LINE, 
	PS_HR_ACCTG_LINE.JRNL_LN_REF, 
	CONVERT(CHAR(10),JOURNAL_DATE, 101) AS PH_REF_01, 
	'JobCode:' + PS_HR_ACCTG_LINE.CHARTFIELD2 AS JobCode, 
	PS_HR_ACCTG_LINE.LINE_DESCR, 
	PS_PERSONAL_DATA.NAME,
	'Status:' + PS_HR_ACCTG_LINE.CHARTFIELD3 AS Status, 
	'' AS FILLER2
FROM         
	PS_HR_ACCTG_LINE LEFT OUTER JOIN
	PS_PERSONAL_DATA ON PS_HR_ACCTG_LINE.JRNL_LN_REF = PS_PERSONAL_DATA.EMPLID





GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

CREATE VIEW dbo.qryJrnlDetails_AMG
AS
-- ADDED 2004/01/31
-- AMIN J.
SELECT     dbo.PS_JRNL_LN.BUSINESS_UNIT, dbo.PS_JRNL_HEADER.FISCAL_YEAR, dbo.PS_JRNL_HEADER.ACCOUNTING_PERIOD, 
                      dbo.PS_JRNL_HEADER.JOURNAL_ID, dbo.PS_JRNL_HEADER.JOURNAL_DATE, dbo.PS_JRNL_HEADER.REVERSAL_CD, 
                      dbo.PS_JRNL_LN.JOURNAL_LINE, dbo.PS_JRNL_LN.JRNL_LN_REF, dbo.PS_JRNL_HEADER.SOURCE, dbo.PS_JRNL_LN.ACCOUNT, 
                      dbo.PS_JRNL_LN.DEPTID, dbo.PS_JRNL_LN.OPERATING_UNIT, dbo.PS_JRNL_LN.FUND_CODE, dbo.PS_JRNL_LN.PROJECT_ID, 
                      dbo.PS_JRNL_LN.CHARTFIELD1, 
		dbo.PS_JRNL_LN.MONETARY_AMOUNT,
		dbo.PS_JRNL_LN.STATISTIC_AMOUNT, 
                      dbo.PS_JRNL_HEADER.JRNL_HDR_STATUS, dbo.PS_JRNL_LN.LINE_DESCR, dbo.qryAMDetails.JRNL_LN_REF AS JRNL_LN_REF2, 
                      dbo.qryAMDetails.PH_REF_CHAR_01, dbo.qryAMDetails.PH_REF_CHAR_02, dbo.qryAMDetails.PH_REF_CHAR_03, dbo.qryAMDetails.PH_REF_CHAR_04, 
                      dbo.qryAMDetails.PH_REF_CHAR_05, dbo.qryAMDetails.PH_REF_CHAR_06 ,
ISNULL(dbo.qryAMDetails.MONETARY_AMOUNT, dbo.PS_JRNL_LN.MONETARY_AMOUNT)  AS  DET_AMT, 
ISNULL(dbo.qryAMDetails.STATISTIC_AMOUNT, dbo.PS_JRNL_LN.STATISTIC_AMOUNT)  AS DET_STAT_AMT
FROM         dbo.PS_JRNL_HEADER INNER JOIN
                      dbo.PS_JRNL_LN ON dbo.PS_JRNL_HEADER.JOURNAL_ID = dbo.PS_JRNL_LN.JOURNAL_ID AND 
                      dbo.PS_JRNL_HEADER.JOURNAL_DATE = dbo.PS_JRNL_LN.JOURNAL_DATE AND 

                      dbo.PS_JRNL_HEADER.BUSINESS_UNIT = dbo.PS_JRNL_LN.BUSINESS_UNIT

                      AND dbo.PS_JRNL_HEADER.UNPOST_SEQ = dbo.PS_JRNL_LN.UNPOST_SEQ
		LEFT OUTER JOIN
                      dbo.qryAMDetails ON dbo.PS_JRNL_LN.JOURNAL_ID = dbo.qryAMDetails.JOURNAL_ID COLLATE Latin1_General_BIN AND 
                      dbo.PS_JRNL_LN.JOURNAL_LINE = dbo.qryAMDetails.JOURNAL_LINE
WHERE     ((dbo.PS_JRNL_HEADER.JRNL_HDR_STATUS = 'P') OR
                      (dbo.PS_JRNL_HEADER.JRNL_HDR_STATUS = 'U')) AND
		(dbo.PS_JRNL_HEADER.SOURCE = 'AMG') AND
			(dbo.PS_JRNL_LN.JRNL_LINE_STATUS <> 1)


GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

CREATE VIEW dbo.qryJrnlDetails_IFX
AS
SELECT      dbo.PS_JRNL_LN.BUSINESS_UNIT, dbo.PS_JRNL_HEADER.FISCAL_YEAR, dbo.PS_JRNL_HEADER.ACCOUNTING_PERIOD, 
                      dbo.PS_JRNL_HEADER.JOURNAL_ID, dbo.PS_JRNL_HEADER.JOURNAL_DATE, dbo.PS_JRNL_HEADER.REVERSAL_CD, 
                      dbo.PS_JRNL_LN.JOURNAL_LINE, dbo.PS_JRNL_LN.JRNL_LN_REF, dbo.PS_JRNL_HEADER.SOURCE, dbo.PS_JRNL_LN.ACCOUNT, 
                      dbo.PS_JRNL_LN.DEPTID, dbo.PS_JRNL_LN.OPERATING_UNIT, dbo.PS_JRNL_LN.FUND_CODE, dbo.PS_JRNL_LN.PROJECT_ID, 
                      dbo.PS_JRNL_LN.CHARTFIELD1, 
		--CASE WHEN PS_JRNL_HEADER.REVERSAL_CD = 'R' THEN dbo.PS_JRNL_LN.MONETARY_AMOUNT * -1 ELSE dbo.PS_JRNL_LN.MONETARY_AMOUNT END AS MONETARY_AMOUNT,
		dbo.PS_JRNL_LN.MONETARY_AMOUNT,
		--CASE WHEN PS_JRNL_HEADER.REVERSAL_CD = 'R' THEN dbo.PS_JRNL_LN.STATISTIC_AMOUNT * -1 ELSE dbo.PS_JRNL_LN.STATISTIC_AMOUNT END AS 
		dbo.PS_JRNL_LN.STATISTIC_AMOUNT, 
                      dbo.PS_JRNL_HEADER.JRNL_HDR_STATUS, dbo.PS_JRNL_LN.LINE_DESCR, dbo.qryIFXDetails.JRNL_LN_REF AS JRNL_LN_REF2, 
                      dbo.qryIFXDetails.PH_REF_CHAR_01, dbo.qryIFXDetails.PH_REF_CHAR_02, dbo.qryIFXDetails.PH_REF_CHAR_03, dbo.qryIFXDetails.PH_REF_CHAR_04, 
                      dbo.qryIFXDetails.PH_REF_CHAR_05, dbo.qryIFXDetails.PH_REF_CHAR_06, 
		ISNULL(CASE WHEN PS_JRNL_HEADER.REVERSAL_CD = 'R'  AND PS_JRNL_HEADER.SYSTEM_SOURCE = 'GOT'
				THEN qryIFXDetails.MONETARY_AMOUNT * -1 ELSE qryIFXDetails.MONETARY_AMOUNT END, 
			CASE WHEN PS_JRNL_HEADER.REVERSAL_CD = 'R'   AND PS_JRNL_HEADER.SYSTEM_SOURCE = 'GOT'
				THEN dbo.PS_JRNL_LN.MONETARY_AMOUNT * -1 ELSE dbo.PS_JRNL_LN.MONETARY_AMOUNT END) AS DET_AMT, 
		ISNULL(CASE WHEN PS_JRNL_HEADER.REVERSAL_CD = 'R'   AND PS_JRNL_HEADER.SYSTEM_SOURCE = 'GOT'
				THEN qryIFXDetails.STATISTIC_AMOUNT * -1 ELSE qryIFXDetails.STATISTIC_AMOUNT END, 
			CASE WHEN PS_JRNL_HEADER.REVERSAL_CD = 'R'   AND PS_JRNL_HEADER.SYSTEM_SOURCE = 'GOT'
				THEN dbo.PS_JRNL_LN.STATISTIC_AMOUNT * -1 ELSE dbo.PS_JRNL_LN.STATISTIC_AMOUNT END) AS DET_STAT_AMT

--dbo.qryIFXDetails.MONETARY_AMOUNT AS  DET_AMT, 
--dbo.qryIFXDetails.STATISTIC_AMOUNT  AS DET_STAT_AMT--,
--dbo.qryIFXDetails.GL_DISTRIB_STATUS
--		ISNULL(dbo.qryIFXDetails.MONETARY_AMOUNT, dbo.PS_JRNL_LN.MONETARY_AMOUNT) AS DET_AMT,
-- 		ISNULL(dbo.qryIFXDetails.STATISTIC_AMOUNT, dbo.PS_JRNL_LN.STATISTIC_AMOUNT)   AS DET_STAT_AMT
FROM         dbo.PS_JRNL_HEADER INNER JOIN
                      dbo.PS_JRNL_LN ON dbo.PS_JRNL_HEADER.JOURNAL_ID = dbo.PS_JRNL_LN.JOURNAL_ID AND 
                      dbo.PS_JRNL_HEADER.JOURNAL_DATE = dbo.PS_JRNL_LN.JOURNAL_DATE AND 

                      dbo.PS_JRNL_HEADER.BUSINESS_UNIT = dbo.PS_JRNL_LN.BUSINESS_UNIT --added 2003/07/14

                       AND dbo.PS_JRNL_HEADER.UNPOST_SEQ = dbo.PS_JRNL_LN.UNPOST_SEQ 
		LEFT OUTER JOIN
                      dbo.qryIFXDetails ON dbo.PS_JRNL_LN.JOURNAL_ID = dbo.qryIFXDetails.JOURNAL_ID COLLATE Latin1_General_BIN AND 
                      dbo.PS_JRNL_LN.JOURNAL_LINE = dbo.qryIFXDetails.JOURNAL_LINE
WHERE     ((dbo.PS_JRNL_HEADER.JRNL_HDR_STATUS = 'P') OR
                      (dbo.PS_JRNL_HEADER.JRNL_HDR_STATUS = 'U')) AND
			(dbo.PS_JRNL_HEADER.SOURCE = 'IFX') AND
			(dbo.PS_JRNL_LN.JRNL_LINE_STATUS <> 1)



























GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

CREATE VIEW dbo.qryJrnlDetails
AS
SELECT     dbo.PS_JRNL_LN.BUSINESS_UNIT, dbo.PS_JRNL_HEADER.FISCAL_YEAR, dbo.PS_JRNL_HEADER.ACCOUNTING_PERIOD, 
                      dbo.PS_JRNL_HEADER.JOURNAL_ID, dbo.PS_JRNL_HEADER.JOURNAL_DATE, dbo.PS_JRNL_HEADER.REVERSAL_CD, 
                      dbo.PS_JRNL_LN.JOURNAL_LINE, dbo.PS_JRNL_LN.JRNL_LN_REF, dbo.PS_JRNL_HEADER.SOURCE, dbo.PS_JRNL_LN.ACCOUNT, 
                      dbo.PS_JRNL_LN.DEPTID, dbo.PS_JRNL_LN.OPERATING_UNIT, dbo.PS_JRNL_LN.FUND_CODE, dbo.PS_JRNL_LN.PROJECT_ID, 
                      dbo.PS_JRNL_LN.CHARTFIELD1, 
		CASE WHEN PS_JRNL_HEADER.REVERSAL_CD = 'R' THEN dbo.PS_JRNL_LN.MONETARY_AMOUNT * -1 ELSE dbo.PS_JRNL_LN.MONETARY_AMOUNT END AS MONETARY_AMOUNT,
		CASE WHEN PS_JRNL_HEADER.REVERSAL_CD = 'R' THEN dbo.PS_JRNL_LN.STATISTIC_AMOUNT * -1 ELSE dbo.PS_JRNL_LN.STATISTIC_AMOUNT END AS STATISTIC_AMOUNT, 
                      dbo.PS_JRNL_HEADER.JRNL_HDR_STATUS, dbo.PS_JRNL_LN.LINE_DESCR, dbo.qryDetails.JRNL_LN_REF AS JRNL_LN_REF2, 
                      dbo.qryDetails.PH_REF_CHAR_01, dbo.qryDetails.PH_REF_CHAR_02, dbo.qryDetails.PH_REF_CHAR_03, dbo.qryDetails.PH_REF_CHAR_04, 
                      dbo.qryDetails.PH_REF_CHAR_05, dbo.qryDetails.PH_REF_CHAR_06, 
		ISNULL(CASE WHEN PS_JRNL_HEADER.REVERSAL_CD = 'R' THEN qryDetails.MONETARY_AMOUNT * -1 ELSE qryDetails.MONETARY_AMOUNT END, CASE WHEN PS_JRNL_HEADER.REVERSAL_CD = 'R' THEN dbo.PS_JRNL_LN.MONETARY_AMOUNT * -1 ELSE dbo.PS_JRNL_LN.MONETARY_AMOUNT END) AS DET_AMT, 
		ISNULL(CASE WHEN PS_JRNL_HEADER.REVERSAL_CD = 'R' THEN qryDetails.STATISTIC_AMOUNT * -1 ELSE qryDetails.STATISTIC_AMOUNT END, CASE WHEN PS_JRNL_HEADER.REVERSAL_CD = 'R' THEN dbo.PS_JRNL_LN.STATISTIC_AMOUNT * -1 ELSE dbo.PS_JRNL_LN.STATISTIC_AMOUNT END) AS DET_STAT_AMT
--		ISNULL(dbo.qryDetails.STATISTIC_AMOUNT, dbo.PS_JRNL_LN.STATISTIC_AMOUNT)   AS DET_STAT_AMT
FROM         dbo.PS_JRNL_HEADER INNER JOIN
                      dbo.PS_JRNL_LN ON dbo.PS_JRNL_HEADER.JOURNAL_ID = dbo.PS_JRNL_LN.JOURNAL_ID AND 
                      dbo.PS_JRNL_HEADER.JOURNAL_DATE = dbo.PS_JRNL_LN.JOURNAL_DATE AND 
                      dbo.PS_JRNL_HEADER.UNPOST_SEQ = dbo.PS_JRNL_LN.UNPOST_SEQ LEFT OUTER JOIN
                      dbo.qryDetails ON dbo.PS_JRNL_LN.JOURNAL_ID = dbo.qryDetails.JOURNAL_ID AND 
                      dbo.PS_JRNL_LN.JOURNAL_LINE = dbo.qryDetails.JOURNAL_LINE
WHERE     (dbo.PS_JRNL_HEADER.JRNL_HDR_STATUS = 'P') OR
                      (dbo.PS_JRNL_HEADER.JRNL_HDR_STATUS = 'U')


GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

CREATE VIEW qryJrnlDetails_PO AS
SELECT     dbo.PS_JRNL_LN.BUSINESS_UNIT, dbo.PS_JRNL_HEADER.FISCAL_YEAR, dbo.PS_JRNL_HEADER.ACCOUNTING_PERIOD, 
                      dbo.PS_JRNL_HEADER.JOURNAL_ID, dbo.PS_JRNL_HEADER.JOURNAL_DATE, dbo.PS_JRNL_HEADER.REVERSAL_CD, 
                      dbo.PS_JRNL_LN.JOURNAL_LINE, dbo.PS_JRNL_LN.JRNL_LN_REF, dbo.PS_JRNL_HEADER.SOURCE, dbo.PS_JRNL_LN.ACCOUNT, 
                      dbo.PS_JRNL_LN.DEPTID, dbo.PS_JRNL_LN.OPERATING_UNIT, dbo.PS_JRNL_LN.FUND_CODE, dbo.PS_JRNL_LN.PROJECT_ID, 
                      dbo.PS_JRNL_LN.CHARTFIELD1, 
                      dbo.PS_JRNL_LN.MONETARY_AMOUNT,
                      dbo.PS_JRNL_LN.STATISTIC_AMOUNT, 
                      dbo.PS_JRNL_HEADER.JRNL_HDR_STATUS, dbo.PS_JRNL_LN.LINE_DESCR, dbo.qryPODetails.JRNL_LN_REF AS JRNL_LN_REF2, 
                      dbo.qryPODetails.PH_REF_CHAR_01, dbo.qryPODetails.PH_REF_CHAR_02, dbo.qryPODetails.PH_REF_CHAR_03, dbo.qryPODetails.PH_REF_CHAR_04, 
                      dbo.qryPODetails.PH_REF_CHAR_05, dbo.qryPODetails.PH_REF_CHAR_06 ,
                      ISNULL(dbo.qryPODetails.MONETARY_AMOUNT, dbo.PS_JRNL_LN.MONETARY_AMOUNT)  AS  DET_AMT, 
                      ISNULL(dbo.qryPODetails.STATISTIC_AMOUNT, dbo.PS_JRNL_LN.STATISTIC_AMOUNT)  AS DET_STAT_AMT
FROM         dbo.PS_JRNL_HEADER INNER JOIN
                      dbo.PS_JRNL_LN ON dbo.PS_JRNL_HEADER.JOURNAL_ID = dbo.PS_JRNL_LN.JOURNAL_ID AND 
                      dbo.PS_JRNL_HEADER.JOURNAL_DATE = dbo.PS_JRNL_LN.JOURNAL_DATE AND 
                      dbo.PS_JRNL_HEADER.BUSINESS_UNIT = dbo.PS_JRNL_LN.BUSINESS_UNIT
                      AND dbo.PS_JRNL_HEADER.UNPOST_SEQ = dbo.PS_JRNL_LN.UNPOST_SEQ
		LEFT OUTER JOIN
                      dbo.qryPODetails ON dbo.PS_JRNL_LN.JOURNAL_ID = dbo.qryPODetails.JOURNAL_ID COLLATE Latin1_General_BIN
						AND dbo.PS_JRNL_LN.JOURNAL_LINE = dbo.qryPODetails.JOURNAL_LINE
WHERE     ((dbo.PS_JRNL_HEADER.JRNL_HDR_STATUS = 'P') OR
                      (dbo.PS_JRNL_HEADER.JRNL_HDR_STATUS = 'U')) AND
                      (dbo.PS_JRNL_HEADER.SOURCE = 'PO') AND
			(dbo.PS_JRNL_LN.JRNL_LINE_STATUS <> 1)




GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

CREATE VIEW dbo.qryJrnlDetails_PYG
AS
SELECT     dbo.PS_JRNL_LN.BUSINESS_UNIT, dbo.PS_JRNL_HEADER.FISCAL_YEAR, dbo.PS_JRNL_HEADER.ACCOUNTING_PERIOD, 
                      dbo.PS_JRNL_HEADER.JOURNAL_ID, dbo.PS_JRNL_HEADER.JOURNAL_DATE, dbo.PS_JRNL_HEADER.REVERSAL_CD, 
                      dbo.PS_JRNL_LN.JOURNAL_LINE, dbo.PS_JRNL_LN.JRNL_LN_REF, dbo.PS_JRNL_HEADER.SOURCE, dbo.PS_JRNL_LN.ACCOUNT, 
                      dbo.PS_JRNL_LN.DEPTID, dbo.PS_JRNL_LN.OPERATING_UNIT, dbo.PS_JRNL_LN.FUND_CODE, dbo.PS_JRNL_LN.PROJECT_ID, 
                      dbo.PS_JRNL_LN.CHARTFIELD1, 
		--CASE WHEN PS_JRNL_HEADER.REVERSAL_CD = 'R' THEN dbo.PS_JRNL_LN.MONETARY_AMOUNT * -1 ELSE dbo.PS_JRNL_LN.MONETARY_AMOUNT END AS MONETARY_AMOUNT,
		--CASE WHEN PS_JRNL_HEADER.REVERSAL_CD = 'R' THEN dbo.PS_JRNL_LN.STATISTIC_AMOUNT * -1 ELSE dbo.PS_JRNL_LN.STATISTIC_AMOUNT END AS STATISTIC_AMOUNT, 
		dbo.PS_JRNL_LN.MONETARY_AMOUNT,
		dbo.PS_JRNL_LN.STATISTIC_AMOUNT,
                      dbo.PS_JRNL_HEADER.JRNL_HDR_STATUS, dbo.PS_JRNL_LN.LINE_DESCR, dbo.qryPYDetails.JRNL_LN_REF AS JRNL_LN_REF2, 
                      dbo.qryPYDetails.PH_REF_CHAR_01, dbo.qryPYDetails.PH_REF_CHAR_02, dbo.qryPYDetails.PH_REF_CHAR_03, dbo.qryPYDetails.PH_REF_CHAR_04, 
                      dbo.qryPYDetails.PH_REF_CHAR_05, dbo.qryPYDetails.PH_REF_CHAR_06, 
		ISNULL(CASE WHEN PS_JRNL_HEADER.REVERSAL_CD = 'R' THEN qryPYDetails.MONETARY_AMOUNT * -1 ELSE qryPYDetails.MONETARY_AMOUNT END, CASE WHEN PS_JRNL_HEADER.REVERSAL_CD = 'R' THEN dbo.PS_JRNL_LN.MONETARY_AMOUNT * -1 ELSE dbo.PS_JRNL_LN.MONETARY_AMOUNT END) AS DET_AMT, 
		ISNULL(CASE WHEN PS_JRNL_HEADER.REVERSAL_CD = 'R' THEN qryPYDetails.STATISTIC_AMOUNT * -1 ELSE qryPYDetails.STATISTIC_AMOUNT END, CASE WHEN PS_JRNL_HEADER.REVERSAL_CD = 'R' THEN dbo.PS_JRNL_LN.STATISTIC_AMOUNT * -1 ELSE dbo.PS_JRNL_LN.STATISTIC_AMOUNT END) AS DET_STAT_AMT
--		ISNULL(dbo.qryPYDetails.STATISTIC_AMOUNT, dbo.PS_JRNL_LN.STATISTIC_AMOUNT)   AS DET_STAT_AMT
FROM         dbo.PS_JRNL_HEADER INNER JOIN
                      dbo.PS_JRNL_LN ON dbo.PS_JRNL_HEADER.JOURNAL_ID = dbo.PS_JRNL_LN.JOURNAL_ID AND 
                      dbo.PS_JRNL_HEADER.JOURNAL_DATE = dbo.PS_JRNL_LN.JOURNAL_DATE AND 

                      dbo.PS_JRNL_HEADER.BUSINESS_UNIT = dbo.PS_JRNL_LN.BUSINESS_UNIT --added 2003/07/14

                      AND dbo.PS_JRNL_HEADER.UNPOST_SEQ = dbo.PS_JRNL_LN.UNPOST_SEQ  --removed 2003/08/05

		LEFT OUTER JOIN
                      dbo.qryPYDetails ON dbo.PS_JRNL_LN.JOURNAL_ID = dbo.qryPYDetails.JOURNAL_ID COLLATE Latin1_General_BIN
						AND dbo.PS_JRNL_LN.JOURNAL_LINE = dbo.qryPYDetails.JOURNAL_LINE
WHERE     ((dbo.PS_JRNL_HEADER.JRNL_HDR_STATUS = 'P') OR
                      (dbo.PS_JRNL_HEADER.JRNL_HDR_STATUS = 'U')) AND
			(dbo.PS_JRNL_HEADER.SOURCE = 'PYG') AND
			(dbo.PS_JRNL_LN.JRNL_LINE_STATUS <> 1)











GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO


SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

CREATE VIEW dbo.z_qryINVTest
AS
SELECT
SC.BUSINESS_UNIT_GL ,
SC.FISCAL_YEAR ,
SC.ACCOUNTING_PERIOD,
SC.JOURNAL_ID,
SC.JOURNAL_DATE,
SC.JOURNAL_LINE,
SC.JRNL_LN_REF,
'ING' AS SOURCE,
SC.ACCOUNT,
SC.DEPTID,
SC.OPERATING_UNIT,
SC.FUND_CODE,
SC.PROJECT_ID,
SC.CHARTFIELD1,
SC.UNIT_MEASURE_STD AS REF_01,
'Order: ' + SC.ORDER_NO AS REF_02,
'Inv Issues:' + convert(char(10),ACCOUNTING_DT,101) AS REF_03,
ITM.DESCR AS REF_04,
'ItemID: ' + SC.INV_ITEM_ID AS REF_05,
'CAT: ' + ITM.CATEGORY_ID + '-' + CAT.DESCR AS REF_06,
SC.MONETARY_AMOUNT AS AMOUNT,
SC.STATISTIC_AMOUNT AS STAT
FROM
PHSAPSD4.FS84TST.dbo.PS_CM_ACCTG_LINE SC LEFT OUTER JOIN
PHSAPSD4.FS84TST.dbo.PS_MASTER_ITEM_TBL ITM ON 
SC.INV_ITEM_ID = ITM.INV_ITEM_ID LEFT OUTER JOIN
PHSAPSD4.FS84TST.dbo.PS_ITM_CAT_TBL CAT ON
CAT.CATEGORY_ID = ITM.CATEGORY_ID AND
CAT.SETID = ITM.SETID

--WHERE SC.DEPTID = '72405010'










GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

