 USE [BPP]
GO

/****** Object:  Index [FactLedger_I01]    Script Date: 01/05/2012 11:59:50 ******/
CREATE NONCLUSTERED INDEX [FactLedger_I01] ON [dbo].[FactLedger] 
(
	[EMPL_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


/****** Object:  Index [FactLedger_I02]    Script Date: 01/05/2012 12:00:02 ******/
CREATE NONCLUSTERED INDEX [FactLedger_I02] ON [dbo].[FactLedger] 
(
	[FUND_CODE] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

USE [BPP]
GO

/****** Object:  Index [FactLedger_I03]    Script Date: 01/05/2012 12:00:22 ******/
CREATE NONCLUSTERED INDEX [FactLedger_I03] ON [dbo].[FactLedger] 
(
	[DEPT_SITE] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

USE [BPP]
GO

/****** Object:  Index [FactLedger_I04]    Script Date: 01/05/2012 12:00:36 ******/
CREATE NONCLUSTERED INDEX [FactLedger_I04] ON [dbo].[FactLedger] 
(
	[BUSINESS_UNIT] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

USE [BPP]
GO

/****** Object:  Index [FactLedger_I05]    Script Date: 01/05/2012 12:00:47 ******/
CREATE NONCLUSTERED INDEX [FactLedger_I05] ON [dbo].[FactLedger] 
(
	[FISCAL_YEAR] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

USE [BPP]
GO

/****** Object:  Index [FactLedger_I06]    Script Date: 01/05/2012 12:00:58 ******/
CREATE NONCLUSTERED INDEX [FactLedger_I06] ON [dbo].[FactLedger] 
(
	[ACCOUNTING_PERIOD] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

USE [BPP]
GO

/****** Object:  Index [FactLedger_I07_Jobcode]    Script Date: 01/05/2012 12:01:11 ******/
CREATE NONCLUSTERED INDEX [FactLedger_I07_Jobcode] ON [dbo].[FactLedger] 
(
	[JOBCODE] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

USE [BPP]
GO

/****** Object:  Index [IX_FactLedger_Dept_site_Account]    Script Date: 01/05/2012 12:01:23 ******/
CREATE NONCLUSTERED INDEX [IX_FactLedger_Dept_site_Account] ON [dbo].[FactLedger] 
(
	[DEPT_SITE] ASC,
	[ACCOUNT] ASC,
	[ACCOUNTING_PERIOD] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

USE [BPP]
GO

/****** Object:  Index [IX_FactLedger_DEPTID]    Script Date: 01/05/2012 12:01:35 ******/
CREATE NONCLUSTERED INDEX [IX_FactLedger_DEPTID] ON [dbo].[FactLedger] 
(
	[DEPTID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

USE [BPP]
GO

/****** Object:  Index [IX_FactLedger_EE_STATUS]    Script Date: 01/05/2012 12:01:47 ******/
CREATE NONCLUSTERED INDEX [IX_FactLedger_EE_STATUS] ON [dbo].[FactLedger] 
(
	[EE_STATUS] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

USE [BPP]
GO

/****** Object:  Index [IX_FactLedger_GRADE]    Script Date: 01/05/2012 12:02:03 ******/
CREATE NONCLUSTERED INDEX [IX_FactLedger_GRADE] ON [dbo].[FactLedger] 
(
	[GRADE] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

USE [BPP]
GO

/****** Object:  Index [IX_FactLedger_HCM_SETID]    Script Date: 01/05/2012 12:02:13 ******/
CREATE NONCLUSTERED INDEX [IX_FactLedger_HCM_SETID] ON [dbo].[FactLedger] 
(
	[HCM_SETID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

USE [BPP]
GO

/****** Object:  Index [IX_FactLedger_PAYCODE]    Script Date: 01/05/2012 12:02:24 ******/
CREATE NONCLUSTERED INDEX [IX_FactLedger_PAYCODE] ON [dbo].[FactLedger] 
(
	[PAYCODE] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

USE [BPP]
GO

/****** Object:  Index [IX_FactLedger_PROJECT_ID]    Script Date: 01/05/2012 12:02:33 ******/
CREATE NONCLUSTERED INDEX [IX_FactLedger_PROJECT_ID] ON [dbo].[FactLedger] 
(
	[PROJECT_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

USE [BPP]
GO

/****** Object:  Index [IX_FactLedger_TRANS_DATE]    Script Date: 01/05/2012 12:02:41 ******/
CREATE NONCLUSTERED INDEX [IX_FactLedger_TRANS_DATE] ON [dbo].[FactLedger] 
(
	[TRANS_DATE] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

USE [BPP]
GO

/****** Object:  Index [IX_FactLedger_UNION_CD]    Script Date: 01/05/2012 12:02:50 ******/
CREATE NONCLUSTERED INDEX [IX_FactLedger_UNION_CD] ON [dbo].[FactLedger] 
(
	[UNION_CD] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


USE [BPP]
GO

/****** Object:  Index [PK_FactLedger]    Script Date: 01/05/2012 12:04:33 *****
ALTER TABLE [dbo].[FactLedger] ADD  CONSTRAINT [PK_FactLedger] PRIMARY KEY CLUSTERED 
(
	[seqno] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

****/
