 Setup /QUIET /ACTION=REBUILDDATABASE /INSTANCENAME=MSSQLSERVER /SQLCOLLATION=Latin1_General_BIN /SQLSYSADMINACCOUNTS=PHSABC\x-james


 "\\10.251.219.1\hssbc_dbs\SQL Installation Media\SQL 2012\Svr_Enterprise_Edtn_2012_English\setup.exe" /QUIET /ACTION=REBUILDDATABASE /INSTANCENAME=SPDBSCL012AG01 /SQLSYSADMINACCOUNTS=PHSABC\x-james